; Variable-width font (VWF) rasterizer.
;
; Composites proportional glyphs into a pool of unique tiles in VRAM bank 1,
; used ONLY for prose surfaces (overworld dialogue, battle messages, Pokedex
; entries). Every other text surface keeps the fixed-width tilemap path.
; GBC-only; on DMG the callers fall back to fixed-width.
;
; This file is INCLUDEd inside SECTION "VWF", ROMX (main.asm), so the code and
; the generated font data share one bank: the compositor reads VWFFontGraphics /
; VWFWidths with no bank switch.
;
; The font data below is generated by tools/make_vwf_font.py from
; gfx/font/font.png (the source of truth). Edit the PNG, not the .1bpp.
; Layout: char codes $80..$FF (idx = code - $80), 128 glyphs.
;   font_vwf.1bpp : 8 bytes/glyph, left-packed 1bpp (bit7 = leftmost, set = ink)
;   vwf_widths.bin: 1 byte/glyph, advance width in pixels (ink width + gap)
;
; How a tile reaches the screen:
;   * the compositor builds a rolling 1bpp shadow (wVWFShadow) in WRAM,
;   * a completed tile's 8 bytes are copied to wVWFCopyBuf and queued,
;   * VWFVBlankCopy (home/vcopy.asm) doubles them 1bpp->2bpp into vVWFPool
;     (rVBK=1) and sets that cell's BG attribute to VWF_ATTR (bank 1),
;   * the cell's tilemap byte (the pool tile index) is written to wTileMap and
;     reaches VRAM via the normal AutoBgMapTransfer.

VWFFontGraphics::
	INCBIN "gfx/font/font_vwf.1bpp"
VWFFontGraphicsEnd::

VWFWidths::
	INCBIN "gfx/font/vwf_widths.bin"
VWFWidthsEnd::

; Per-line start addresses for the dialogue/battle prose box (Stage 1: 2 lines).
VWFLineCellPtrs: ; WRAM tilemap cell of each line's first prose column
	dw wTileMap + VWF_DLG_ROW0 * SCREEN_WIDTH + VWF_DLG_STARTCOL
	dw wTileMap + (VWF_DLG_ROW0 + VWF_DLG_ROWSTEP) * SCREEN_WIDTH + VWF_DLG_STARTCOL
VWFLineAttrPtrs: ; bank-1 attribute cell of each line's first prose column.
; The OVERWORLD message box is drawn on the WINDOW layer (vBGMap1), so attributes
; go to the window map's bank-1 attribute plane, not vBGMap0.
	dw vBGMap1 + VWF_DLG_ROW0 * TILEMAP_WIDTH + VWF_DLG_STARTCOL
	dw vBGMap1 + (VWF_DLG_ROW0 + VWF_DLG_ROWSTEP) * TILEMAP_WIDTH + VWF_DLG_STARTCOL
VWFLinePoolBase: ; pool tile index of each line's first column
	db 0
	db VWF_DLG_COLS


; Reset compositor state for a fresh prose box and seed line 0.
; Does not touch VRAM; cells stay blank (spaces) until each tile flushes.
VWFInitPool::
	xor a
	ld [wVWFWordLen], a   ; fresh dialogue: drop any word left buffered by an aborted box
	ld [wVWFWordWidth], a ; (else a stale word composites into the next dialogue)
	; fall through to the page setup, which KEEPS the buffer (so auto-page can re-flush
	; the word that overflowed onto the new page).
VWFNewPage::
	xor a
	ld [wVWFPenX], a
	ld [wVWFLine], a
	ld [wVWFCurPoolTile], a
	call VWFSeedLine
	call VWFClearSpaceTile
	; fall through to clear the shadow
VWFClearShadow:
	ld hl, wVWFShadow
	ld bc, 16
	xor a
.loop
	ld [hli], a
	dec bc
	ld a, b
	or c
	ld a, 0
	jr nz, .loop
	ret

; Point wVWFCellPtr / wVWFAttrPtr / wVWFCurPoolTile at the start of line wVWFLine.
VWFSeedLine:
	ld a, [wVWFLine]
	ld e, a
	ld d, 0
	ld hl, VWFLinePoolBase
	add hl, de
	ld a, [hl]
	ld [wVWFCurPoolTile], a
	; cell ptr
	ld hl, VWFLineCellPtrs
	add hl, de
	add hl, de
	ld a, [hli]
	ld [wVWFCellPtr], a
	ld a, [hl]
	ld [wVWFCellPtr + 1], a
	; attr ptr: the window-map (vBGMap1) attribute cell for this line
	call VWFAttrTable
	add hl, de
	add hl, de
	ld a, [hli]
	ld [wVWFAttrPtr], a
	ld a, [hl]
	ld [wVWFAttrPtr + 1], a
	ret

; hl = the per-line window-map (vBGMap1) attribute-cell table. BOTH overworld and
; battle render the message box on the WINDOW: in battle the window covers the
; whole screen (rWY=0), so the box and its attributes live on the window, not the
; BG. (A BG-targeted table writes to the hidden BG layer, leaving the visible
; window cells at bank-0 -> they fetch the font and show "ABCDEF…".)
VWFAttrTable:
	ld hl, VWFLineAttrPtrs
	ret

; Zero bank-1 pool tile $7F (the tile that prose cells reference while still
; showing the space byte). Keeps the brief window between attribute-set and the
; lagging AutoBgMapTransfer of the tile byte rendering as blank, not garbage.
VWFClearSpaceTile:
	di
.wait
	ldh a, [rLY]
	cp $90
	jr c, .wait ; wait for VBlank to touch VRAM bank 1
	ld a, 1
	ldh [rVBK], a
	ld hl, vVWFPool + $7F * 16
	xor a
	ld b, 16
.clr
	ld [hli], a
	dec b
	jr nz, .clr
	xor a
	ldh [rVBK], a
	ei
	ret


; Composite the character at [de] at the pen, advance the pen, and flush a tile
; if a tile boundary is crossed. Preserves de (the text pointer).
; The character to composite is passed in E by the caller (home/text.asm). It is
; read there with the correct ROM bank + SVBK, because the farcall to this ROMX
; routine switches the ROM bank to the VWF bank, so a `[de]` read here would hit
; the wrong bank for ROM text (a cross-bank read bug). This routine then runs
; with SVBK=2 to reach the VWF state in bank 2 (a plain farcall; it toggles SVBK
; itself rather than via vwf_farcall).
; STAGE 2 word-wrap. The text engine BUFFERS each word's chars (VWFAddChar) and
; flushes the word at a word boundary (VWFFlushWord), which measures it and starts a
; new line if it would overflow. Buffering (not peek-ahead) is what makes inserts +
; gen-1 text compression wrap correctly: they all feed chars through this same path.
; All three run with SVBK=2 (set by the caller's vwf_farcall).

; Composite ONE glyph (char in c) at the pen, advance, flush the tile on a boundary.
; Assumes SVBK=2. (The old immediate-composite body; now driven per buffered glyph.)
VWFCompositeGlyph:
	ld a, [wVWFPenX]
	cp VWF_DLG_LINEWIDTH
	ret nc ; safety clamp: a word wider than a whole line is dropped past the edge
	       ; rather than spraying VRAM (can't fit anywhere; auto-wrap already tried)
	ld a, c ; char
	cp ' '
	jr z, .space
	cp VWF_FIRST_CODE
	jr c, .space
	sub VWF_FIRST_CODE
	ld c, a
	ld b, 0
	ld hl, VWFWidths
	add hl, bc
	ld a, [hl]
	push af
	ld hl, VWFFontGraphics
	sla c
	rl b
	sla c
	rl b
	sla c
	rl b
	add hl, bc
	call VWFComposite
	pop af
	jr .advance
.space
	ld a, VWF_SPACE_WIDTH
.advance
	ld b, a
	ld a, [wVWFPenX]
	ld c, a
	add b
	ld [wVWFPenX], a
	and $F8
	ld b, a
	ld a, c
	and $F8
	cp b
	ret z
	jp VWFFlushAndAdvanceTile

; Buffer char e into the current word + accumulate its pixel width. No display yet;
; the word is composited (revealed) when VWFFlushWord runs at the next boundary.
VWFAddChar::
	ld a, [wVWFWordLen]
	cp VWF_WORD_BUFSIZE
	jr c, .room
	push de
	call VWFFlushWord ; pathological over-long word: place what we have, keep going
	pop de
.room
	ld a, [wVWFWordLen]
	ld c, a
	ld b, 0
	ld hl, wVWFWordBuf
	add hl, bc
	ld [hl], e ; store the char
	inc a
	ld [wVWFWordLen], a ; len++
	ld a, e ; accumulate the glyph's advance width
	cp ' '
	jr z, .spaceW
	cp VWF_FIRST_CODE
	jr c, .spaceW
	sub VWF_FIRST_CODE
	ld c, a
	ld b, 0
	ld hl, VWFWidths
	add hl, bc
	ld a, [hl]
	jr .addW
.spaceW
	ld a, VWF_SPACE_WIDTH
.addW
	ld b, a
	ld a, [wVWFWordWidth]
	add b
	ld [wVWFWordWidth], a
	ret

; Flush the buffered word: if it won't fit on what's left of the line, break to the
; next line first (clamped on the last line until auto-page lands); otherwise add the
; separating space; then composite the word. Resets the buffer. No-op when empty
; (so leading / repeated spaces collapse).
VWFFlushWord::
	xor a
	ld [wUnusedFlag], a ; default: word placed, no page. wUnusedFlag = the VWF auto-page
	                    ; signal -- a WRAM0/bank-independent byte readable by the home
	                    ; caller at SVBK=1 (farcall clobbers b, so a register can't carry
	                    ; it back; it's genuinely unused except a dead cable-club write).
	ld a, [wVWFWordLen]
	and a
	ret z
	ld a, [wVWFPenX]
	and a
	jr z, .place ; line start: no leading space
	ld b, a ; b = penX
	ld a, [wVWFWordWidth]
	add VWF_SPACE_WIDTH
	jr c, .needBreak ; >255 -> can't possibly fit
	add b
	jr c, .needBreak
	ld b, a ; b = required width = penX + space + word
	; this line's pixel budget: the full box, except the LAST line keeps col 18 free for
	; the ▼ "more" arrow (row 16). The top line(s) have no arrow, so they use all 18 cols.
	ld a, [wVWFLine]
	cp VWF_DLG_LINES - 1
	ld a, VWF_DLG_LINEWIDTH
	jr c, .haveBudget
	ld a, VWF_DLG_LINEWIDTH - 8 ; last line: reserve the ▼ column
.haveBudget
	cp b
	jr nc, .leadingSpace ; budget >= required -> the word fits on this line
.needBreak
	; word won't fit on the rest of this line. If we're on the LAST line the box is full:
	; signal home to PAGE (it shows the ▼, waits, clears, then re-flushes this still-
	; buffered word onto the fresh page). Otherwise just advance to the next line.
	ld a, [wVWFLine]
	cp VWF_DLG_LINES - 1
	jr c, .doBreak
	ld a, 1
	ld [wUnusedFlag], a ; page needed; leave the word buffered for the re-flush
	ret
.doBreak
	call VWFLineBreak ; advance to the next line, penX -> 0
	jr .place
.leadingSpace
	ld c, ' '
	call VWFCompositeGlyph
.place
	ld a, [wVWFWordLen]
	ld e, a ; e = remaining glyph count
	ld hl, wVWFWordBuf
.loop
	ld a, [hli]
	push hl
	push de
	ld c, a
	call VWFCompositeGlyph
	pop de
	pop hl
	dec e
	jr nz, .loop
	xor a
	ld [wVWFWordLen], a
	ld [wVWFWordWidth], a
	ret

; OR the 8-row glyph bitmap at hl into the rolling shadow, shifted right by
; (penX & 7). High byte -> current tile half, low byte -> next tile half.
VWFComposite:
	ld a, [wVWFPenX]
	and 7
	ld [wVWFTmpShift], a
	ld de, wVWFShadow
	ld c, 8 ; row counter
.row
	ld a, [hli]
	push hl ; save bitmap ptr
	ld h, a
	ld l, 0 ; hl = glyph row << 8
	ld a, [wVWFTmpShift]
	and a
	jr z, .noShift
	ld b, a
.shift
	srl h
	rr l
	dec b
	jr nz, .shift
.noShift
	; h = high (this tile), l = low (next tile); OR into shadow
	ld a, [de]
	or h
	ld [de], a ; shadow[row] |= high
	push de
	ld a, e
	add 8
	ld e, a
	jr nc, .nocarry
	inc d
.nocarry
	ld a, [de]
	or l
	ld [de], a ; shadow[row + 8] |= low
	pop de
	inc de
	pop hl
	dec c
	jr nz, .row
	ret

; A tile boundary was crossed: queue the just-completed tile (shadow[0..7]) for
; its cell, slide the overflow half down, and advance to the next pool tile.
VWFFlushAndAdvanceTile:
	call VWFQueueFlush
	; slide shadow[8..15] -> [0..7], clearing the top half
	ld hl, wVWFShadow + 8
	ld de, wVWFShadow
	ld b, 8
.slide
	ld a, [hl]
	ld [de], a
	ld [hl], 0
	inc hl
	inc de
	dec b
	jr nz, .slide
	; advance pool tile and cell/attr pointers
	ld hl, wVWFCurPoolTile
	inc [hl]
	ld hl, wVWFCellPtr
	inc [hl]
	jr nz, .cellOk
	inc hl
	inc [hl]
	jr .attr
.cellOk
	inc hl ; skip cell hi
.attr
	ld hl, wVWFAttrPtr
	inc [hl]
	ret nz
	inc hl
	inc [hl]
	ret

; Finalize the current partial tile (call at end of string / before a break /
; before a prompt) so its glyphs are displayed.
VWFFlushCurrent::
	ld a, [wVWFPenX]
	and 7
	ret z ; tile-aligned: nothing pending
	jp VWFQueueFlush

; Queue shadow[0..7] -> the current pool tile, and write the cell's tilemap byte
; now (bank 0, via AutoBgMapTransfer). The attribute is applied in VBlank.
VWFQueueFlush:
	; Hard safety clamp: never flush a pool tile past the box. This bounds
	; wVWFCopyDest (pool), wVWFCellPtr (wTileMap) and wVWFAttrPtr (BG attr map)
	; so a runaway can never spray VRAM/WRAM (the whole-screen corruption + crash).
	ld a, [wVWFCurPoolTile]
	cp VWF_DLG_LINES * VWF_DLG_COLS
	ret nc
	; Write the composited tile (1bpp -> 2bpp), its attribute, its window-map tile
	; byte, AND its wTileMap byte ALL inside one interrupt-disabled block, so
	; AutoBgMapTransfer (which runs in VBlank) can never observe a half-updated
	; cell (the inter-page garbage flash). Bounded busy-wait for a safe VRAM
	; window: no halt / DelayFrame (which could hang if interrupts are off), and
	; LCD-off is handled so the wait can't spin.
	di
	ldh a, [rLCDC]
	add a ; bit 7 (LCD enable) -> carry
	jr nc, .safe ; LCD off: VRAM is freely accessible
.waitVBlank
	ldh a, [rLY]
	cp $90
	jr c, .waitVBlank ; LCD on guarantees rLY advances, so this terminates
.safe
	ld a, 1
	ldh [rVBK], a ; VRAM bank 1
	; pool pixels
	ld a, [wVWFCurPoolTile]
	ld l, a
	ld h, 0
	add hl, hl
	add hl, hl
	add hl, hl
	add hl, hl ; * 16
	ld bc, vVWFPool
	add hl, bc
	ld e, l
	ld d, h ; de = pool tile address (bank 1)
	ld hl, wVWFShadow
	ld b, 8
.copy
	ld a, [hli]
	ld [de], a ; low bitplane
	inc de
	ld [de], a ; high bitplane (ink = color 3)
	inc de
	dec b
	jr nz, .copy
	; attribute (bank 1), at the window-map cell
	ld a, [wVWFAttrPtr]
	ld l, a
	ld a, [wVWFAttrPtr + 1]
	ld h, a
	ld [hl], VWF_ATTR
	; window-map tile byte (bank 0), same cell
	xor a
	ldh [rVBK], a
	ld a, [wVWFCurPoolTile]
	add VWF_TILE_BASE
	ld c, a ; c = tile number ($80 + pool index)
	ld [hl], a ; hl = window-map cell (bank 0)
	; wTileMap byte (WRAM): the overworld textbox window is fed from wTileMap via a
	; copy, so the box only shows if this is written. It MUST stay in sync with the
	; attr/window cell above (same row/col) -- VWFSeedLine seeds both together.
	ld hl, wVWFCellPtr
	ld a, [hli]
	ld h, [hl]
	ld l, a
	ld [hl], c
	ei
	ret


; Hard line break (manual <LINE>/<NEXT> in VWF mode): finalize the current line,
; advance to the next line (clamped), and reseed. No auto-wrap yet.
VWFLineBreak::
	call VWFFlushCurrent
	ld a, [wVWFLine]
	cp VWF_DLG_LINES - 1
	jr nc, .clamp ; already on the last line: stay (Stage 2 adds scroll)
	inc a
	ld [wVWFLine], a
.clamp
	xor a
	ld [wVWFPenX], a
	call VWFSeedLine
	jp VWFClearShadow

; Paragraph / page break in VWF mode: clear the pool cells and restart at line 0.
; (Stage 1 also routes <CONT>/<SCROLL> here; real scrolling comes in Stage 2.)
VWFParagraph::
	call VWFFlushCurrent
	call VWFEndBox ; clear attrs + blank the prose cells
	jp VWFInitPool

; Tear down / clear the prose box: blank every prose cell so it reverts to the
; fixed-width path. Three passes, all atomic, to avoid the inter-page flash:
;  (1) window-map attribute = 0 (bank 1),
;  (2) window-map tile byte = space (bank 0) -- matches the direct byte the flush
;      writes there, so the clear is immediate not lagged,
;  (3) wTileMap byte = space (WRAM) so AutoBgMapTransfer reasserts the same value.
; Safe to call even if no VWF box was open.
VWFEndBox::
	di
.waitVBlank
	ldh a, [rLY]
	cp $90
	jr c, .waitVBlank ; wait until VBlank to touch VRAM
	; pass 1: clear attributes (active layer's map, bank 1)
	ld a, 1
	ldh [rVBK], a
	call VWFAttrTable
	xor a
	call VWFFillBoxFromTable
	; pass 2: blank the layer's map tile bytes (same cells, bank 0)
	xor a
	ldh [rVBK], a
	call VWFAttrTable
	ld a, ' '
	call VWFFillBoxFromTable
	; pass 3: blank the WRAM tilemap box cells (the window is fed from wTileMap), so
	; the box clears. Uses VWFLineCellPtrs (rows 14/16) -- the real box position.
	ld hl, VWFLineCellPtrs
	ld a, ' '
	call VWFFillBoxFromTable
	ei
	ret
; Fill the whole prose box with the byte in A. hl = a dw-per-line address table
; (each entry is a line's first cell address); writes VWF_DLG_COLS bytes per line.
VWFFillBoxFromTable:
	ld d, a ; d = fill value (held across lines)
	ld b, VWF_DLG_LINES
.lineLoop
	ld a, [hli]
	ld e, a ; e = cell lo
	ld a, [hli] ; a = cell hi; hl now at the next line's table entry
	push hl ; save table ptr
	ld h, a
	ld l, e ; hl = this line's cell address
	ld a, d ; fill value
	ld c, VWF_DLG_COLS
.fill
	ld [hli], a
	dec c
	jr nz, .fill
	pop hl ; restore table ptr (advanced to next line)
	dec b
	jr nz, .lineLoop
	ret
