; Variable-width font (VWF) rasterizer.
;
; Composites proportional glyphs into a pool of unique tiles in VRAM bank 1,
; used ONLY for prose surfaces (overworld dialogue, battle messages, Pokedex
; entries). Every other text surface keeps the fixed-width tilemap path.
; GBC-only; on DMG the callers fall back to fixed-width.
;
; This file is INCLUDEd inside SECTION "VWF", ROMX (main.asm), so the code and
; the generated font data share one bank: the compositor reads VWFFontGraphics /
; VWFWidths with no bank switch.
;
; The font data below is generated by tools/make_vwf_font.py from
; gfx/font/font.png (the source of truth). Edit the PNG, not the .1bpp.
; Layout: char codes $80..$FF (idx = code - $80), 128 glyphs.
;   font_vwf.1bpp : 8 bytes/glyph, left-packed 1bpp (bit7 = leftmost, set = ink)
;   vwf_widths.bin: 1 byte/glyph, advance width in pixels (ink width + gap)
;
; How a tile reaches the screen:
;   * the compositor builds a rolling 1bpp shadow (wVWFShadow) in WRAM,
;   * a completed tile's 8 bytes are copied to wVWFCopyBuf and queued,
;   * VWFVBlankCopy (home/vcopy.asm) doubles them 1bpp->2bpp into vVWFPool
;     (rVBK=1) and sets that cell's BG attribute to VWF_ATTR (bank 1),
;   * the cell's tilemap byte (the pool tile index) is written to wTileMap and
;     reaches VRAM via the normal AutoBgMapTransfer.

VWFFontGraphics::
	INCBIN "gfx/font/font_vwf.1bpp"
VWFFontGraphicsEnd::

VWFWidths::
	INCBIN "gfx/font/vwf_widths.bin"
VWFWidthsEnd::

; Per-line start addresses for the dialogue/battle prose box (mode 0: 2 lines, WINDOW).
VWFLineCellPtrs: ; WRAM tilemap cell of each line's first prose column
	dw wTileMap + VWF_DLG_ROW0 * SCREEN_WIDTH + VWF_DLG_STARTCOL
	dw wTileMap + (VWF_DLG_ROW0 + VWF_DLG_ROWSTEP) * SCREEN_WIDTH + VWF_DLG_STARTCOL
VWFLineAttrPtrs: ; bank-1 attribute cell of each line's first prose column.
; The OVERWORLD message box is drawn on the WINDOW layer (vBGMap1), so attributes
; go to the window map's bank-1 attribute plane, not vBGMap0.
	dw vBGMap1 + VWF_DLG_ROW0 * TILEMAP_WIDTH + VWF_DLG_STARTCOL
	dw vBGMap1 + (VWF_DLG_ROW0 + VWF_DLG_ROWSTEP) * TILEMAP_WIDTH + VWF_DLG_STARTCOL
VWFLinePoolBase: ; pool tile index of each line's first column
	db 0
	db VWF_DLG_COLS

; Per-line start addresses for the Pokedex description box (mode 1: 6 lines, rows 11..16,
; packed). Drawn on the BG (vBGMap0), inside the blue panel -- NOT the window.
VWFLineCellPtrsDex:
FOR n, VWF_DEX_LINES
	dw wTileMap + (VWF_DEX_ROW0 + n * VWF_DEX_ROWSTEP) * SCREEN_WIDTH + VWF_DLG_STARTCOL
ENDR
VWFLineAttrPtrsDex:
FOR n, VWF_DEX_LINES
	dw vBGMap0 + (VWF_DEX_ROW0 + n * VWF_DEX_ROWSTEP) * TILEMAP_WIDTH + VWF_DLG_STARTCOL
ENDR
VWFLinePoolBaseDex:
FOR n, VWF_DEX_LINES
	db n * VWF_DEX_COLS ; 19 pool tiles per line (4 lines = 76, fits the $80-$FF pool)
ENDR

; Per-mode config records copied into the wVWFBox* WRAM block by VWFInitPool / VWFInitPoolDex.
; Layout MUST match the WRAM order: mode, lines, poolMax, attr, cellTbl, attrTbl, poolTbl (10 bytes).
DEF VWF_CFG_SIZE EQU 10
VWFConfigDialogue:
	db 0
	db VWF_DLG_LINES
	db VWF_DLG_LINES * VWF_DLG_COLS
	db VWF_ATTR
	dw VWFLineCellPtrs
	dw VWFLineAttrPtrs
	dw VWFLinePoolBase
VWFConfigDex:
	db 1
	db VWF_DEX_LINES
	db VWF_DEX_LINES * VWF_DEX_COLS
	db VWF_DEX_ATTR
	dw VWFLineCellPtrsDex
	dw VWFLineAttrPtrsDex
	dw VWFLinePoolBaseDex


; Open a Pokedex (mode 1) prose box: load the 6-line dex geometry, then init like any box.
VWFInitPoolDex::
	ld hl, VWFConfigDex
	jr VWFInitPoolWithConfig
; Battle message box: PrintText redraws the box's TILE BYTES but not its bank-1
; ATTRIBUTES, and battle has NO per-message VWFEndBox (one box reused across messages),
; so a prior message's VWF attributes would linger under the new text. Wipe the box
; (attrs + bytes) first, then fall into the normal pool reset.
VWFInitPoolBattle::
	call VWFEndBox
	; fall through
; Reset compositor state for a fresh prose box and seed line 0.
; Does not touch VRAM; cells stay blank (spaces) until each tile flushes.
VWFInitPool::
	ld hl, VWFConfigDialogue ; default = dialogue/battle 2-line WINDOW box
VWFInitPoolWithConfig:
	call VWFApplyConfig   ; copy the per-mode geometry into the wVWFBox* block
	xor a
	ld [wVWFWordLen], a   ; fresh box: drop any word left buffered by an aborted box
	ld [wVWFWordWidth], a ; (else a stale word composites into the next box)
	; fall through to the page setup, which KEEPS the buffer (so auto-page can re-flush
	; the word that overflowed onto the new page).
VWFNewPage::
	xor a
	ld [wVWFPenX], a
	ld [wVWFLine], a
	ld [wVWFCurPoolTile], a
	ld [wVWFScrollPhase], a ; a fresh box/page starts at phase 0 (line0=pool[0..], line1=pool[18..])
	call VWFSeedLine
	call VWFClearSpaceTile
	; fall through to clear the shadow
VWFClearShadow:
	ld hl, wVWFShadow
	ld bc, 16
	xor a
.loop
	ld [hli], a
	dec bc
	ld a, b
	or c
	ld a, 0
	jr nz, .loop
	ret

; Copy the VWF_CFG_SIZE-byte geometry record at hl into the wVWFBox* WRAM block
; (mode, lines, poolMax, attr, cellTbl, attrTbl, poolTbl). SVBK=2.
VWFApplyConfig:
	ld de, wVWFBoxMode
	ld c, VWF_CFG_SIZE
.copy
	ld a, [hli]
	ld [de], a
	inc de
	dec c
	jr nz, .copy
	ret

; Close the Pokedex box: blank its cells using the active (dex) geometry, then restore the
; dialogue config so a later overworld/battle VWFEndBox clears the right (2-line) box and a
; stale mode-1 can't make it wipe rows 11..16 of a battle/overworld screen. SVBK=2.
VWFCloseBoxDex::
	call VWFEndBox
	ld hl, VWFConfigDialogue
	jr VWFApplyConfig

; Point wVWFCellPtr / wVWFAttrPtr / wVWFCurPoolTile at the start of line wVWFLine.
; Reads the active box's per-line tables from the cached pointers (wVWFCellTbl etc.).
VWFSeedLine:
	; pool base ping-pongs with the scroll phase: display line L reads pool half (L XOR phase),
	; so a scroll shows the old bottom line on top by just flipping the phase (no VRAM copy).
	; (Mode 1 never scrolls, so phase stays 0 and the index is just the line, 0..5.)
	ld a, [wVWFPoolTbl]
	ld l, a
	ld a, [wVWFPoolTbl + 1]
	ld h, a
	ld a, [wVWFLine]
	ld e, a
	ld a, [wVWFScrollPhase]
	xor e
	ld e, a
	ld d, 0
	add hl, de
	ld a, [hl]
	ld [wVWFCurPoolTile], a
	; cell ptr: the cell table indexed by 2 * display line
	ld a, [wVWFCellTbl]
	ld l, a
	ld a, [wVWFCellTbl + 1]
	ld h, a
	ld a, [wVWFLine]
	ld e, a
	ld d, 0
	add hl, de
	add hl, de
	ld a, [hli]
	ld [wVWFCellPtr], a
	ld a, [hl]
	ld [wVWFCellPtr + 1], a
	; attr ptr: the attribute-cell table (window vBGMap1 for mode 0, BG vBGMap0 for the dex)
	call VWFAttrTable
	add hl, de
	add hl, de
	ld a, [hli]
	ld [wVWFAttrPtr], a
	ld a, [hl]
	ld [wVWFAttrPtr + 1], a
	ret

; hl = the active box's per-line attribute-cell table. Mode 0 (dialogue/battle) renders the
; box on the WINDOW (vBGMap1): in battle the window covers the whole screen (rWY=0), so the
; box and its attributes live on the window, not the BG. (A BG-targeted table there would
; write to the hidden BG layer, leaving the visible window cells at bank-0 -> they fetch the
; font and show "ABCDEF…".) Mode 1 (Pokedex) renders on the BG (vBGMap0) inside the panel.
VWFAttrTable:
	ld a, [wVWFAttrTbl]
	ld l, a
	ld a, [wVWFAttrTbl + 1]
	ld h, a
	ret

; hl = the active box's per-line wTileMap cell table (VWFLineCellPtrs / ...Dex).
VWFCellTable:
	ld a, [wVWFCellTbl]
	ld l, a
	ld a, [wVWFCellTbl + 1]
	ld h, a
	ret

; Zero bank-1 pool tile $7F (the tile that prose cells reference while still
; showing the space byte). Keeps the brief window between attribute-set and the
; lagging AutoBgMapTransfer of the tile byte rendering as blank, not garbage.
VWFClearSpaceTile:
	di
	ldh a, [rLCDC]
	add a ; bit 7 (LCD enable) -> carry
	jr nc, .safe ; LCD OFF (e.g. the intro fades): VRAM is free; rLY is frozen so a
	             ; wait-for-VBlank would HANG forever (the intro white-screen). Skip it.
.wait
	ldh a, [rLY]
	cp $90
	jr c, .wait ; wait for VBlank to touch VRAM bank 1
.safe
	ld a, 1
	ldh [rVBK], a
	ld hl, vVWFPool + $7F * 16
	xor a
	ld b, 16
.clr
	ld [hli], a
	dec b
	jr nz, .clr
	xor a
	ldh [rVBK], a
	ei
	ret


; Composite the character at [de] at the pen, advance the pen, and flush a tile
; if a tile boundary is crossed. Preserves de (the text pointer).
; The character to composite is passed in E by the caller (home/text.asm). It is
; read there with the correct ROM bank + SVBK, because the farcall to this ROMX
; routine switches the ROM bank to the VWF bank, so a `[de]` read here would hit
; the wrong bank for ROM text (a cross-bank read bug). This routine then runs
; with SVBK=2 to reach the VWF state in bank 2 (a plain farcall; it toggles SVBK
; itself rather than via vwf_farcall).
; STAGE 2 word-wrap. The text engine BUFFERS each word's chars (VWFAddChar) and
; flushes the word at a word boundary (VWFFlushWord), which measures it and starts a
; new line if it would overflow. Buffering (not peek-ahead) is what makes inserts +
; gen-1 text compression wrap correctly: they all feed chars through this same path.
; All three run with SVBK=2 (set by the caller's vwf_farcall).

; a = the active box's pixel line width: dialogue/battle = 144 (18 cols), Pokedex = 152 (19 cols).
; Clobbers only a. Reads wVWFBoxMode (bank 2 -> callers run at SVBK=2).
VWFActiveLineWidth:
	ld a, [wVWFBoxMode]
	and a
	ld a, VWF_DLG_LINEWIDTH
	ret z
	ld a, VWF_DEX_LINEWIDTH
	ret

; Composite ONE glyph (char in c) at the pen, advance, flush the tile on a boundary.
; Assumes SVBK=2. (The old immediate-composite body; now driven per buffered glyph.)
VWFCompositeGlyph:
	call VWFActiveLineWidth
	ld b, a
	ld a, [wVWFPenX]
	cp b
	ret nc ; safety clamp: a word wider than a whole line is dropped past the edge
	       ; rather than spraying VRAM (can't fit anywhere; auto-wrap already tried)
	ld a, c ; char
	cp ' '
	jr z, .space
	cp VWF_FIRST_CODE
	jr c, .space
	sub VWF_FIRST_CODE
	ld c, a
	ld b, 0
	ld hl, VWFWidths
	add hl, bc
	ld a, [hl]
	push af
	ld hl, VWFFontGraphics
	sla c
	rl b
	sla c
	rl b
	sla c
	rl b
	add hl, bc
	call VWFComposite
	pop af
	jr .advance
.space
	ld a, VWF_SPACE_WIDTH
.advance
	ld b, a
	ld a, [wVWFPenX]
	ld c, a
	add b
	ld [wVWFPenX], a
	and $F8
	ld b, a
	ld a, c
	and $F8
	cp b
	ret z
	jp VWFFlushAndAdvanceTile

; Buffer char e into the current word + accumulate its pixel width. No display yet;
; the word is composited (revealed) when VWFFlushWord runs at the next boundary.
VWFAddChar::
	ld a, [wVWFWordLen]
	cp VWF_WORD_BUFSIZE
	jr c, .room
	push de
	call VWFFlushWord ; pathological over-long word: place what we have, keep going
	pop de
.room
	ld a, [wVWFWordLen]
	ld c, a
	ld b, 0
	ld hl, wVWFWordBuf
	add hl, bc
	ld [hl], e ; store the char
	inc a
	ld [wVWFWordLen], a ; len++
	ld a, e ; accumulate the glyph's advance width
	cp ' '
	jr z, .spaceW
	cp VWF_FIRST_CODE
	jr c, .spaceW
	sub VWF_FIRST_CODE
	ld c, a
	ld b, 0
	ld hl, VWFWidths
	add hl, bc
	ld a, [hl]
	jr .addW
.spaceW
	ld a, VWF_SPACE_WIDTH
.addW
	ld b, a
	ld a, [wVWFWordWidth]
	add b
	ld [wVWFWordWidth], a
	ret

; Flush the buffered word: if it won't fit on what's left of the line, break to the
; next line first (clamped on the last line until auto-page lands); otherwise add the
; separating space; then composite the word. Resets the buffer. No-op when empty
; (so leading / repeated spaces collapse).
VWFFlushWord::
	xor a
	ld [wVWFPageAction], a ; default: word placed, no page. wVWFPageAction = the VWF auto-page
	                    ; signal -- a WRAM0/bank-independent byte readable by the home
	                    ; caller at SVBK=1 (farcall clobbers b, so a register can't carry
	                    ; it back; it's genuinely unused except a dead cable-club write).
	ld a, [wVWFWordLen]
	and a
	ret z
	ld a, [wVWFPenX]
	and a
	jr z, .place ; line start: no leading space
	ld b, a ; b = penX
	ld a, [wVWFWordWidth]
	add VWF_SPACE_WIDTH
	jr c, .needBreak ; >255 -> can't possibly fit
	add b
	jr c, .needBreak
	ld b, a ; b = required width = penX + space + word
	; this line's pixel budget: the full box width (mode-aware: 144 dialogue / 152 dex), except
	; the LAST line keeps the rightmost column free for the ▼ "more" arrow. Top lines use it all.
	call VWFActiveLineWidth
	ld d, a ; d = box line width (held across the carry-setting cp below)
	ld a, [wVWFBoxLines]
	dec a
	ld c, a ; c = last line index of the active box
	ld a, [wVWFLine]
	cp c
	ld a, d
	jr c, .haveBudget ; not the last line: full width
	sub 8 ; last line: reserve the ▼ column
.haveBudget
	cp b
	jr nc, .leadingSpace ; budget >= required -> the word fits on this line
.needBreak
	; word won't fit on the rest of this line. If we're on the LAST line the box is full:
	; signal home to advance -- mode 0 SCROLLS one line; mode != 0 (dex) PAGES (shows the ▼,
	; waits, clears, then re-flushes this still-buffered word onto the fresh page). Otherwise
	; just advance to the next line.
	ld a, [wVWFBoxLines]
	dec a
	ld b, a ; b = last line index
	ld a, [wVWFLine]
	cp b
	jr c, .doBreak
	ld a, [wVWFBoxMode]
	and a
	ld a, 1 ; mode 0 -> wVWFPageAction = 1 (scroll)
	jr z, .signalOverflow
	ld a, 2 ; mode != 0 -> wVWFPageAction = 2 (page)
.signalOverflow
	ld [wVWFPageAction], a ; overflow action; leave the word buffered for the re-flush
	ret
.doBreak
	call VWFLineBreak ; advance to the next line, penX -> 0
	jr .place
.leadingSpace
	; Sunsette: closing punctuation (! ? . ,) glues to the previous word, so it must NOT get a
	; leading space. Without this, a separate punctuation segment (e.g. "X used <move>" + "!", or
	; "level " + <num> + "!") rendered as "<move> !" / "level 6 !". Skip the space for those.
	ld a, [wVWFWordBuf] ; first char of the buffered word (SVBK=2 here, so this reads bank 2)
	cp '!'
	jr z, .place
	cp '?'
	jr z, .place
	cp '.'
	jr z, .place
	cp ','
	jr z, .place
	ld c, ' '
	call VWFCompositeGlyph
.place
	ld a, [wVWFWordLen]
	ld e, a ; e = remaining glyph count
	ld hl, wVWFWordBuf
.loop
	ld a, [hli]
	push hl
	push de
	ld c, a
	call VWFCompositeGlyph
	pop de
	pop hl
	dec e
	jr nz, .loop
	xor a
	ld [wVWFWordLen], a
	ld [wVWFWordWidth], a
	ret

; OR the 8-row glyph bitmap at hl into the rolling shadow, shifted right by
; (penX & 7). High byte -> current tile half, low byte -> next tile half.
VWFComposite:
	ld a, [wVWFPenX]
	and 7
	ld [wVWFTmpShift], a
	ld de, wVWFShadow
	ld c, 8 ; row counter
.row
	ld a, [hli]
	push hl ; save bitmap ptr
	ld h, a
	ld l, 0 ; hl = glyph row << 8
	ld a, [wVWFTmpShift]
	and a
	jr z, .noShift
	ld b, a
.shift
	srl h
	rr l
	dec b
	jr nz, .shift
.noShift
	; h = high (this tile), l = low (next tile); OR into shadow
	ld a, [de]
	or h
	ld [de], a ; shadow[row] |= high
	push de
	ld a, e
	add 8
	ld e, a
	jr nc, .nocarry
	inc d
.nocarry
	ld a, [de]
	or l
	ld [de], a ; shadow[row + 8] |= low
	pop de
	inc de
	pop hl
	dec c
	jr nz, .row
	ret

; A tile boundary was crossed: queue the just-completed tile (shadow[0..7]) for
; its cell, slide the overflow half down, and advance to the next pool tile.
VWFFlushAndAdvanceTile:
	call VWFQueueFlush
	; slide shadow[8..15] -> [0..7], clearing the top half
	ld hl, wVWFShadow + 8
	ld de, wVWFShadow
	ld b, 8
.slide
	ld a, [hl]
	ld [de], a
	ld [hl], 0
	inc hl
	inc de
	dec b
	jr nz, .slide
	; advance pool tile and cell/attr pointers
	ld hl, wVWFCurPoolTile
	inc [hl]
	ld hl, wVWFCellPtr
	inc [hl]
	jr nz, .cellOk
	inc hl
	inc [hl]
	jr .attr
.cellOk
	inc hl ; skip cell hi
.attr
	ld hl, wVWFAttrPtr
	inc [hl]
	ret nz
	inc hl
	inc [hl]
	ret

; Finalize the current partial tile (call at end of string / before a break /
; before a prompt) so its glyphs are displayed.
VWFFlushCurrent::
	ld a, [wVWFPenX]
	and 7
	ret z ; tile-aligned: nothing pending
	jp VWFQueueFlush

; Queue shadow[0..7] -> the current pool tile, and write the cell's tilemap byte
; now (bank 0, via AutoBgMapTransfer). The attribute is applied in VBlank.
VWFQueueFlush:
	; Hard safety clamp: never flush a pool tile past the box. This bounds
	; wVWFCopyDest (pool), wVWFCellPtr (wTileMap) and wVWFAttrPtr (BG attr map)
	; so a runaway can never spray VRAM/WRAM (the whole-screen corruption + crash).
	ld a, [wVWFBoxPoolMax]
	ld b, a
	ld a, [wVWFCurPoolTile]
	cp b
	ret nc
	; Write the composited tile (1bpp -> 2bpp), its attribute, its window-map tile
	; byte, AND its wTileMap byte ALL inside one interrupt-disabled block, so
	; AutoBgMapTransfer (which runs in VBlank) can never observe a half-updated
	; cell (the inter-page garbage flash). Bounded busy-wait for a safe VRAM
	; window: no halt / DelayFrame (which could hang if interrupts are off), and
	; LCD-off is handled so the wait can't spin.
	di
	ldh a, [rLCDC]
	add a ; bit 7 (LCD enable) -> carry
	jr nc, .safe ; LCD off: VRAM is freely accessible
.waitVBlank
	ldh a, [rLY]
	cp $90
	jr c, .waitVBlank ; LCD on guarantees rLY advances, so this terminates
.safe
	ld a, 1
	ldh [rVBK], a ; VRAM bank 1
	; pool pixels
	ld a, [wVWFCurPoolTile]
	ld l, a
	ld h, 0
	add hl, hl
	add hl, hl
	add hl, hl
	add hl, hl ; * 16
	ld bc, vVWFPool
	add hl, bc
	ld e, l
	ld d, h ; de = pool tile address (bank 1)
	ld hl, wVWFShadow
	ld b, 8
.copy
	ld a, [hli]
	ld [de], a ; low bitplane
	inc de
	ld [de], a ; high bitplane (ink = color 3)
	inc de
	dec b
	jr nz, .copy
	; attribute (bank 1), at the active box's attribute cell (window or BG plane)
	ld a, [wVWFAttrPtr]
	ld l, a
	ld a, [wVWFAttrPtr + 1]
	ld h, a
	ld a, [wVWFBoxAttr]
	ld [hl], a
	; window-map tile byte (bank 0), same cell
	xor a
	ldh [rVBK], a
	ld a, [wVWFCurPoolTile]
	add VWF_TILE_BASE
	ld c, a ; c = tile number ($80 + pool index)
	ld [hl], a ; hl = window-map cell (bank 0)
	; wTileMap byte (WRAM): the overworld textbox window is fed from wTileMap via a
	; copy, so the box only shows if this is written. It MUST stay in sync with the
	; attr/window cell above (same row/col) -- VWFSeedLine seeds both together.
	ld hl, wVWFCellPtr
	ld a, [hli]
	ld h, [hl]
	ld l, a
	ld [hl], c
	ei
	ret


; Hard line break (manual <LINE>/<NEXT> in VWF mode): finalize the current line,
; advance to the next line (clamped), and reseed. No auto-wrap yet.
VWFLineBreak::
	call VWFFlushCurrent
	ld a, [wVWFBoxLines]
	dec a
	ld b, a ; b = last line index of the active box
	ld a, [wVWFLine]
	cp b
	jr nc, .clamp ; already on the last line: stay (auto-overflow scrolls/pages)
	inc a
	ld [wVWFLine], a
.clamp
	xor a
	ld [wVWFPenX], a
	call VWFSeedLine
	jp VWFClearShadow

; Paragraph / page break in VWF mode: clear the pool cells and restart at line 0.
; (Stage 1 also routes <CONT>/<SCROLL> here; real scrolling comes in Stage 2.)
VWFParagraph::
	call VWFFlushCurrent
	call VWFEndBox ; clear attrs + blank the prose cells
	jp VWFInitPool

; True scroll (ping-pong). COPY the bottom display row's cells (its filled pool-tile refs AND
; its trailing blanks) up onto the top row, so the top mirrors the bottom EXACTLY -- no stale
; leftovers where the new top line is shorter. Then blank the bottom row, flip wVWFScrollPhase
; (so the compositor's next bottom line uses the now-free pool half instead of the one the top
; row is displaying), and reseed on the bottom row. No VRAM pixel copy; fits one VBlank. SVBK=2.
;
; .copyRow (de=dst row addr, hl=src row addr) copies VWF_DLG_COLS bytes at the current rVBK.
VWFScroll::
	call VWFFlushCurrent ; finalize the bottom row's partial tile before scrolling
	di
	ldh a, [rLCDC]
	add a ; LCD enable -> carry
	jr nc, .safe
.wait
	ldh a, [rLY]
	cp $90
	jr c, .wait
.safe
	; wTileMap (WRAM): bottom row -> top row
	ld hl, VWFLineCellPtrs      ; [0] = top (dst)
	ld a, [hli]
	ld e, a
	ld d, [hl]
	ld hl, VWFLineCellPtrs + 2  ; [1] = bottom (src)
	ld a, [hli]
	ld h, [hl]
	ld l, a
	call .copyRow
	; window-map tile bytes (bank 0): bottom -> top
	xor a
	ldh [rVBK], a
	call .copyAttrRow
	; window-map attributes (bank 1): bottom -> top
	ld a, 1
	ldh [rVBK], a
	call .copyAttrRow
	; --- blank the BOTTOM row (fresh for new text): attrs=0 (bank1), tile byte=space (bank0), wTileMap=space ---
	ld hl, VWFLineAttrPtrs + 2
	ld a, [hli]
	ld h, [hl]
	ld l, a
	push hl
	xor a            ; attr 0 (still rVBK=1)
	ld b, VWF_DLG_COLS
.botAttr
	ld [hli], a
	dec b
	jr nz, .botAttr
	xor a
	ldh [rVBK], a    ; bank 0 for the tile bytes
	pop hl
	ld a, ' '
	ld b, VWF_DLG_COLS
.botWin
	ld [hli], a
	dec b
	jr nz, .botWin
	ld hl, VWFLineCellPtrs + 2
	ld a, [hli]
	ld h, [hl]
	ld l, a
	ld a, ' '
	ld b, VWF_DLG_COLS
.botMap
	ld [hli], a
	dec b
	jr nz, .botMap
	ei
	; flip the phase so the new bottom line composites into the freed pool half (not the one now
	; shown on top), then continue on the bottom display row.
	ld a, [wVWFScrollPhase]
	xor 1
	ld [wVWFScrollPhase], a
	ld a, 1
	ld [wVWFLine], a
	xor a
	ld [wVWFPenX], a
	call VWFSeedLine
	jp VWFClearShadow

; copy VWF_DLG_COLS bytes from the BOTTOM vBGMap1 row to the TOP vBGMap1 row at the current
; rVBK (VWFLineAttrPtrs[1] -> [0]); then fall into .copyRow.
.copyAttrRow:
	ld hl, VWFLineAttrPtrs      ; [0] = top (dst)
	ld a, [hli]
	ld e, a
	ld d, [hl]
	ld hl, VWFLineAttrPtrs + 2  ; [1] = bottom (src)
	ld a, [hli]
	ld h, [hl]
	ld l, a
	; fall through
.copyRow:
	ld b, VWF_DLG_COLS
.cr
	ld a, [hli]
	ld [de], a
	inc de
	dec b
	jr nz, .cr
	ret

; Re-assert VWF_ATTR (bank 1) on every box cell that still holds a pool tile byte ($80+).
; A battle attribute reload (BGMapAttributes_Battle, e.g. ShakeEnemyHUD / center-stage SEs)
; stomps the box rows back to bank 0, so the pool tiles render as bank-0 FONT glyphs (the
; "alphabet" flash) until the next message. This keeps the displayed message intact (unlike
; VWFEndBox, which blanks it). Reads the tile byte from wTileMap (bank-independent) and only
; touches pool cells, so space/border cells are left alone. SVBK=2. Caller gates on GBC +
; wVWFBoxOpen so it only runs when a VWF battle message is actually on screen.
VWFReapplyBoxAttrs::
	di
	ldh a, [rLCDC]
	add a ; LCD enable -> carry
	jr nc, .safe ; LCD off: VRAM free
.wait
	ldh a, [rLY]
	cp $90
	jr c, .wait
.safe
	ld a, 1
	ldh [rVBK], a ; bank 1 (attribute plane) for the whole pass
	; row 0: de = vBGMap1 cell (attr, write), hl = wTileMap cell (tile byte, read)
	ld hl, VWFLineAttrPtrs
	ld a, [hli]
	ld e, a
	ld d, [hl]
	ld hl, VWFLineCellPtrs
	ld a, [hli]
	ld h, [hl]
	ld l, a
	call .doRow
	; row 1
	ld hl, VWFLineAttrPtrs + 2
	ld a, [hli]
	ld e, a
	ld d, [hl]
	ld hl, VWFLineCellPtrs + 2
	ld a, [hli]
	ld h, [hl]
	ld l, a
	call .doRow
	xor a
	ldh [rVBK], a
	ei
	ret
.doRow:
	ld c, VWF_DLG_COLS
.dcell
	ld a, [hli] ; wTileMap tile byte (bank-independent read)
	cp VWF_TILE_BASE
	jr c, .dnext ; < $80: space / border -> leave its attribute
	ld a, VWF_ATTR
	ld [de], a ; vBGMap1 attribute (bank 1)
.dnext
	inc de
	dec c
	jr nz, .dcell
	ret

; Tear down / clear the prose box: blank every prose cell so it reverts to the
; fixed-width path. Three passes, all atomic, to avoid the inter-page flash:
;  (1) window-map attribute = 0 (bank 1),
;  (2) window-map tile byte = space (bank 0) -- matches the direct byte the flush
;      writes there, so the clear is immediate not lagged,
;  (3) wTileMap byte = space (WRAM) so AutoBgMapTransfer reasserts the same value.
; Safe to call even if no VWF box was open.
VWFEndBox::
	ld a, [wVWFBoxLines]
	and a
	ret z ; no box ever configured (lines = 0 at boot, before the first VWFInitPool): nothing
	      ; to clear, and a 0 line-count would underflow VWFFillBoxFromTable into a 256-line spray.
	di
	ldh a, [rLCDC]
	add a ; bit 7 (LCD enable) -> carry
	jr nc, .safe ; LCD OFF: rLY frozen, so the wait below would hang. VRAM is free; skip it.
.waitVBlank
	ldh a, [rLY]
	cp $90
	jr c, .waitVBlank ; wait until VBlank to touch VRAM
.safe
	; pass 1: reset attributes to the box's BLANK attr (palette bits, bank 0 = fixed-width
	; layer). For dialogue that's 0 (palette 0); for the dex it's $02 (the blue panel palette),
	; so cleared cells keep the panel colour instead of reverting to palette 0.
	ld a, 1
	ldh [rVBK], a
	call VWFAttrTable
	ld a, [wVWFBoxAttr]
	and $07
	call VWFFillBoxFromTable
	; pass 2: blank the layer's map tile bytes (same cells, bank 0)
	xor a
	ldh [rVBK], a
	call VWFAttrTable
	ld a, ' '
	call VWFFillBoxFromTable
	; pass 3: blank the WRAM tilemap box cells (the layer is fed from wTileMap), so the box
	; clears. Uses the active box's cell table (mode 0 rows 14/16, mode 1 rows 11..16).
	call VWFCellTable
	ld a, ' '
	call VWFFillBoxFromTable
	ei
	ret
; Fill the whole prose box with the byte in A. hl = a dw-per-line address table
; (each entry is a line's first cell address); writes VWF_DLG_COLS bytes per line.
VWFFillBoxFromTable:
	ld d, a ; d = fill value (held across lines)
	ld a, [wVWFBoxLines]
	ld b, a ; b = line count of the active box
.lineLoop
	ld a, [hli]
	ld e, a ; e = cell lo
	ld a, [hli] ; a = cell hi; hl now at the next line's table entry
	push hl ; save table ptr
	ld h, a
	ld l, e ; hl = this line's cell address
	ld a, [wVWFBoxMode] ; clear the active box's full width: 18 cols dialogue, 19 cols dex
	and a
	ld a, VWF_DLG_COLS
	jr z, .cols
	ld a, VWF_DEX_COLS
.cols
	ld c, a
	ld a, d ; fill value
.fill
	ld [hli], a
	dec c
	jr nz, .fill
	pop hl ; restore table ptr (advanced to next line)
	dec b
	jr nz, .lineLoop
	ret

; Prepare the Pokedex "more pages" arrow as POOL tiles. The dex is displayed on the WINDOW
; (vBGMap1) and every visible prose cell is a bank-1 pool tile fetched under attribute $0A; the
; panel's attribute map is fixed at $0A and the only thing that reaches the window is the tile
; byte (via wTileMap -> AutoBgMapTransfer). So a bank-0 font '▼' / an attribute flip can never
; show (the flip lands on the hidden BG, and on the window the cell stays attr $0A = a blank pool
; tile). The fix: render the arrow the SAME way as the prose -- as a bank-1 pool tile. This copies
; the regular-font '▼' (bank 0, tile $EE -> $8EE0 under $8800 addressing) into the first FREE pool
; tile (index = poolMax, just past the prose), and zeroes the next one as the blink-OFF blank.
; VWFDexPageWait then just sets the cell's tile byte to VWF_DEX_ARROW_TILE / VWF_DEX_BLANK_TILE.
; VBlank-safe (di + LCD-off / VBlank wait), like the compositor. Only on the dex page path.
VWFDexArrowPrep::
	di
	ldh a, [rLCDC]
	add a ; bit 7 (LCD enable) -> carry
	jr nc, .safe ; LCD off: VRAM is freely accessible
.wait
	ldh a, [rLY]
	cp $90
	jr c, .wait ; wait for VBlank before touching VRAM
.safe
	ld hl, $8EE0 ; bank 0: the regular font '▼' (tile $EE in $8800 signed addressing)
	ld de, vVWFPool + (VWF_DEX_LINES * VWF_DEX_COLS) * 16 ; bank 1: first free pool tile (the arrow)
	ld b, 16
.copy
	xor a
	ldh [rVBK], a ; bank 0 to read the font glyph
	ld a, [hl]
	ld c, a
	ld a, 1
	ldh [rVBK], a ; bank 1 to write the pool tile
	ld a, c
	ld [de], a
	inc hl
	inc de
	dec b
	jr nz, .copy
	; de now points at the next pool tile (still bank 1): zero it = the blink-OFF blank
	ld b, 16
	xor a
.zero
	ld [de], a
	inc de
	dec b
	jr nz, .zero
	xor a
	ldh [rVBK], a ; restore bank 0
	ei
	ret
