; Auto-generated by tools/gen_pokemon_data.py from the base-stats pages. Do not edit by hand.
; SSOT = data/pokemon/base_stats/<species>.asm  (;@ evo / ;@ learn / ;@ learn_like / ;@ evo_move).
; The EvosMovesPointerTable order (internal species ids) and its sharing are preserved verbatim.
; Evos+moves data structure:
; - Evolution methods: db EVOLVE_LEVEL, level, species / db EVOLVE_ITEM, item, 1, species / db EVOLVE_TRADE, 1, species
; - db 0 ; no more evolutions
; - Learnset (increasing level order): db level, move   (level EVO_MOVE_LEVEL = learned on evolution)
; - db 0 ; no more level-up moves

EvosMovesPointerTable:
	table_width 2, EvosMovesPointerTable
	dw RhydonEvosMoves
	dw KangaskhanEvosMoves
	dw NidoranMEvosMoves
	dw ClefairyEvosMoves
	dw SpearowEvosMoves
	dw VoltorbEvosMoves
	dw NidokingEvosMoves
	dw SlowbroEvosMoves
	dw IvysaurEvosMoves
	dw ExeggutorEvosMoves
	dw LickitungEvosMoves
	dw ExeggcuteEvosMoves
	dw GrimerEvosMoves
	dw GengarEvosMoves
	dw NidoranFEvosMoves
	dw NidoqueenEvosMoves
	dw CuboneEvosMoves
	dw RhyhornEvosMoves
	dw LaprasEvosMoves
	dw ArcanineEvosMoves
	dw MewEvosMoves
	dw GyaradosEvosMoves
	dw ShellderEvosMoves
	dw TentacoolEvosMoves
	dw GastlyEvosMoves
	dw ScytherEvosMoves
	dw StaryuEvosMoves
	dw BlastoiseEvosMoves
	dw PinsirEvosMoves
	dw TangelaEvosMoves
	dw NothingEvosMoves ; torched
	dw NothingEvosMoves
	dw GrowlitheEvosMoves
	dw OnixEvosMoves
	dw FearowEvosMoves
	dw PidgeyEvosMoves
	dw SlowpokeEvosMoves
	dw KadabraEvosMoves
	dw GravelerEvosMoves
	dw ChanseyEvosMoves
	dw MachokeEvosMoves
	dw MrMimeEvosMoves
	dw HitmonleeEvosMoves
	dw HitmonchanEvosMoves
	dw ArbokEvosMoves
	dw ParasectEvosMoves
	dw PsyduckEvosMoves
	dw DrowzeeEvosMoves
	dw GolemEvosMoves
	dw NothingEvosMoves ; irradiated
	dw MagmarEvosMoves
	dw MagmarEvosMoves ; volcanic magmar
	dw ElectabuzzEvosMoves
	dw MagnetonEvosMoves
	dw KoffingEvosMoves
	dw MagnetonEvosMoves ; floating magneton
	dw MankeyEvosMoves
	dw SeelEvosMoves
	dw DiglettEvosMoves
	dw TaurosEvosMoves
	dw NothingEvosMoves
	dw NothingEvosMoves
	dw NothingEvosMoves
	dw FarfetchdEvosMoves
	dw VenonatEvosMoves
	dw DragoniteEvosMoves
	dw NothingEvosMoves
	dw NothingEvosMoves
	dw NothingEvosMoves
	dw DoduoEvosMoves
	dw PoliwagEvosMoves
	dw JynxEvosMoves
	dw MoltresEvosMoves
	dw ArticunoEvosMoves
	dw ZapdosEvosMoves
	dw DittoEvosMoves
	dw MeowthEvosMoves
	dw KrabbyEvosMoves
	dw NothingEvosMoves
	dw NothingEvosMoves
	dw NothingEvosMoves
	dw VulpixEvosMoves
	dw NinetalesEvosMoves
	dw PikachuEvosMoves
	dw RaichuEvosMoves
	dw NothingEvosMoves ; chunky
	dw NothingEvosMoves
	dw DratiniEvosMoves
	dw DragonairEvosMoves
	dw KabutoEvosMoves
	dw KabutopsEvosMoves
	dw HorseaEvosMoves
	dw SeadraEvosMoves
	dw WinterDragonairEvosMoves
	dw NothingEvosMoves
	dw SandshrewEvosMoves
	dw SandslashEvosMoves
	dw OmanyteEvosMoves
	dw OmastarEvosMoves
	dw JigglypuffEvosMoves
	dw WigglytuffEvosMoves
	dw EeveeEvosMoves
	dw FlareonEvosMoves
	dw JolteonEvosMoves
	dw VaporeonEvosMoves
	dw MachopEvosMoves
	dw ZubatEvosMoves
	dw EkansEvosMoves
	dw ParasEvosMoves
	dw PoliwhirlEvosMoves
	dw PoliwrathEvosMoves
	dw WeedleEvosMoves
	dw KakunaEvosMoves
	dw BeedrillEvosMoves
	dw NothingEvosMoves ; painless
	dw DodrioEvosMoves
	dw PrimeapeEvosMoves
	dw DugtrioEvosMoves
	dw VenomothEvosMoves
	dw DewgongEvosMoves
	dw NothingEvosMoves
	dw NothingEvosMoves
	dw CaterpieEvosMoves
	dw MetapodEvosMoves
	dw ButterfreeEvosMoves
	dw MachampEvosMoves
	dw NothingEvosMoves
	dw GolduckEvosMoves
	dw HypnoEvosMoves
	dw GolbatEvosMoves
	dw MewtwoEvosMoves
	dw SnorlaxEvosMoves
	dw MagikarpEvosMoves
	dw NothingEvosMoves ; the maw
	dw NothingEvosMoves
	dw MukEvosMoves
	dw NothingEvosMoves
	dw KinglerEvosMoves
	dw CloysterEvosMoves
	dw NothingEvosMoves
	dw ElectrodeEvosMoves
	dw ClefableEvosMoves
	dw WeezingEvosMoves
	dw PersianEvosMoves
	dw MarowakEvosMoves
	dw WeezingEvosMoves ; floating weezing
	dw HaunterEvosMoves
	dw AbraEvosMoves
	dw AlakazamEvosMoves
	dw PidgeottoEvosMoves
	dw PidgeotEvosMoves
	dw StarmieEvosMoves
	dw BulbasaurEvosMoves
	dw VenusaurEvosMoves
	dw TentacruelEvosMoves
	dw NothingEvosMoves
	dw GoldeenEvosMoves
	dw SeakingEvosMoves
	dw NothingEvosMoves
	dw NothingEvosMoves
	dw NothingEvosMoves
	dw NothingEvosMoves
	dw PonytaEvosMoves
	dw RapidashEvosMoves
	dw RattataEvosMoves
	dw RaticateEvosMoves
	dw NidorinoEvosMoves
	dw NidorinaEvosMoves
	dw GeodudeEvosMoves
	dw PorygonEvosMoves
	dw AerodactylEvosMoves
	dw OnixEvosMoves ; hardened onix - shares ONIX's learnset (falls through like the other variants)
	dw MagnemiteEvosMoves
	dw MewtwoEvosMoves
	dw GengarEvosMoves ; powered haunter
	dw CharmanderEvosMoves
	dw SquirtleEvosMoves
	dw CharmeleonEvosMoves
	dw WartortleEvosMoves
	dw CharizardEvosMoves
	dw NothingEvosMoves ; real missingno
	dw NothingEvosMoves ; Fossil Kabutops
	dw NothingEvosMoves ; Fossil aerodactyl
	dw NothingEvosMoves ; GHOST
	dw OddishEvosMoves
	dw GloomEvosMoves
	dw VileplumeEvosMoves
	dw BellsproutEvosMoves
	dw WeepinbellEvosMoves
	dw VictreebelEvosMoves
	assert_table_length NUM_POKEMON_INDEXES

RhydonEvosMoves:
; Evolutions
	db 0
; Learnset
	db 8, ROCK_THROW
	db 12, BITE
	db 15, DOUBLE_KICK
	db 19, METEOR_HORN
	db 23, MUD_BOMB
	db 27, ROCK_ON
	db 36, PISTON_KICK
	db 39, ROCK_SLIDE
	db 42, EARTHQUAKE
	db 47, METAMORPHIC
	db 52, AIR_DRILL
	db 56, SPIKE_CANNON
	db 0

KangaskhanEvosMoves:
; Evolutions
	db 0
; Learnset
	db 18, BITE
	db 23, STOMP
	db 27, DOUBLE_KICK
	db 30, MACH_PUNCH
	db 36, REST
	db 39, DOUBLE_EDGE
	db 41, FOCUS_ENERGY
	db 44, DIZZY_PUNCH
	db 52, SHORYUKEN
	db 56, COMBOBREAKER
	db 0

NidoranMEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 16, NIDORINO
	db 0
; Learnset
	db 8, POISON_STING
	db 12, DOUBLE_KICK
	db 16, SAND_ATTACK
	db 20, MUD_BOMB
	db 25, METEOR_HORN
	db 30, STOMP
	db 35, FOCUS_ENERGY
	db 40, EARTHQUAKE
	db 46, REST
	db 52, VENOM_DRILL
	db 58, PISTON_KICK
	db 0

ClefairyEvosMoves:
; Evolutions
	db EVOLVE_ITEM, MOON_STONE, 1, CLEFABLE
	db 0
; Learnset
	db 13, SING
	db 15, DOUBLESLAP
	db 17, METRONOME
	db 21, PSYBEAM
	db 25, LIGHT_SCREEN
	db 28, MIMIC
	db 33, LOVELY_KISS
	db 38, PSYCHIC_M
	db 45, AURORA_MIST
	db 54, SENBONZAKURA
	db 59, TRI_ATTACK
	db 65, MINIMIZE
	db 0

SpearowEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 20, FEAROW
	db 0
; Learnset
	db 9, LEER
	db 13, MUD_CLAW
	db 18, WING_ATTACK
	db 22, ILL_WIND
	db 26, MOCKINGBIRD
	db 30, BLOOD_RUSH
	db 33, AIR_DRILL
	db 37, PHANTASM
	db 42, AGILITY
	db 48, DOUBLE_EDGE
	db 55, SPIKE_CANNON
	db 0

VoltorbEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 27, ELECTRODE
	db 0
; Learnset
	db 15, THUNDER_WAVE
	db 18, SPARK
	db 22, SWIFT
	db 24, HEAT_RUSH
	db 28, SCREECH
	db 31, THUNDERBOLT
	db 35, EGG_BOMB
	db 39, SUPERNOVA
	db 42, EXPLOSION
	db 48, THUNDER
	db 0

NidokingEvosMoves:
; Evolutions
	db 0
; Learnset
	db 8, POISON_STING
	db 12, DOUBLE_KICK
	db 16, SAND_ATTACK
	db 20, MUD_BOMB
	db 25, METEOR_HORN
	db 30, STOMP
	db 35, FOCUS_ENERGY
	db 40, EARTHQUAKE
	db 46, REST
	db 52, VENOM_DRILL
	db 58, PISTON_KICK
	db 0

SlowbroEvosMoves:
; Evolutions
	db 0
; Learnset
	db 12, CONFUSION
	db 17, DISABLE
	db 20, HEADBUTT
	db 24, CLAMP
	db 28, PSYBEAM
	db 32, SHELL_GAME
	db 36, SLUDGE_BOMB
	db 41, CALM_MIND
	db 45, PSYCHIC_M
	db 0

IvysaurEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 32, VENUSAUR
	db 0
; Learnset
	db 6, LEECH_SEED
	db 8, VINE_WHIP
	db 11, POISONPOWDER
	db 14, ADAPTATION
	db 18, STUN_SPORE
	db 21, RAZOR_LEAF
	db 25, EMETIC_PURGE
	db 33, SLEEP_POWDER
	db 38, VENOM_LASH
	db 45, SENBONZAKURA
	db 52, TOXIC
	db 0

ExeggutorEvosMoves:
; Evolutions
	db 0
; Learnset
	db 14, LEECH_SEED
	db 18, MEGA_DRAIN
	db 20, STUN_SPORE
	db 23, PSYBEAM
	db 27, SHADOW_BALL
	db 32, RAZOR_LEAF
	db 36, PSYCHIC_M
	db 48, ADAPTATION
	db 53, EGG_BOMB
	db 60, SOLARBEAM
	db 0

LickitungEvosMoves:
; Evolutions
	db 0
; Learnset
	db 10, WRAP
	db 13, DISABLE
	db 17, STOMP
	db 20, LEECH_LIFE
	db 23, MIMIC
	db 28, REST
	db 31, DIZZY_PUNCH
	db 37, ADAPTATION
	db 42, POWER_BIND
	db 50, VENOM_LASH
	db 0

ExeggcuteEvosMoves:
; Evolutions
	db EVOLVE_ITEM, LEAF_STONE, 1, EXEGGUTOR
	db 0
; Learnset
	db 14, LEECH_SEED
	db 18, MEGA_DRAIN
	db 20, STUN_SPORE
	db 23, PSYBEAM
	db 27, SHADOW_BALL
	db 32, RAZOR_LEAF
	db 34, SOFTBOILED
	db 36, PSYCHIC_M
	db 48, ADAPTATION
	db 53, EGG_BOMB
	db 60, SOLARBEAM
	db 0

GrimerEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 30, MUK
	db 0
; Learnset
	db 14, ACID
	db 23, HARDEN
	db 26, MUD_BOMB
	db 29, MINIMIZE
	db 33, BODY_SLAM
	db 37, SLUDGE_BOMB
	db 41, RECOVER
	db 46, MAXIMIZE
	db 50, DOUBLE_EDGE
	db 55, VENOM_LASH
	db 0

GengarEvosMoves:
; Evolutions
	db 0
; Learnset
	db 21, PHANTASM
	db 24, HYPNOSIS
	db 29, EMETIC_PURGE
	db 33, CONFUSE_RAY
	db 41, SHADOW_BOX
	db 46, DOUBLE_TEAM
	db 51, MAXIMIZE
	db 57, SOULSTEALER
	db 0

NidoranFEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 16, NIDORINA
	db 0
; Learnset
	db 8, POISON_STING
	db 12, MUD_BOMB
	db 16, SAND_ATTACK
	db 20, BULK_UP
	db 25, BLOOD_RUSH
	db 30, BODY_SLAM
	db 35, BARRIER
	db 40, EARTHQUAKE
	db 46, REST
	db 52, SLUDGE_BOMB
	db 58, METEOR_DRIVE
	db 0

NidoqueenEvosMoves:
; Evolutions
	db 0
; Learnset
	db 8, POISON_STING
	db 12, MUD_BOMB
	db 16, SAND_ATTACK
	db 20, BULK_UP
	db 25, BLOOD_RUSH
	db 30, BODY_SLAM
	db 35, BARRIER
	db 40, EARTHQUAKE
	db 46, REST
	db 52, SLUDGE_BOMB
	db 58, METEOR_DRIVE
	db 0

CuboneEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 28, MAROWAK
	db 0
; Learnset
	db 14, FOCUS_ENERGY
	db 18, SCREECH
	db 22, LIGHT_SCREEN
	db 25, PHANTASM
	db 27, HEADBUTT
	db 30, DIG
	db 33, MACH_PUNCH
	db 36, SHADOW_BOX
	db 40, BONEMERANG
	db 45, METEOR_DRIVE
	db 50, COMBOBREAKER
	db 0

RhyhornEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 33, RHYDON
	db 0
; Learnset
	db 8, ROCK_THROW
	db 12, BITE
	db 15, DOUBLE_KICK
	db 19, METEOR_HORN
	db 23, MUD_BOMB
	db 27, ROCK_ON
	db 36, PISTON_KICK
	db 39, ROCK_SLIDE
	db 42, EARTHQUAKE
	db 47, METAMORPHIC
	db 52, AIR_DRILL
	db 56, SPIKE_CANNON
	db 0

LaprasEvosMoves:
; Evolutions
	db 0
; Learnset
	db 30, BODY_SLAM
	db 33, CONFUSE_RAY
	db 36, AURORA_MIST
	db 38, ICE_BEAM
	db 46, HYDRO_PUMP
	db 53, BLIZZARD
	db 0

ArcanineEvosMoves:
; Evolutions
	db 0
; Learnset
	db 7, BITE
	db 10, LICK
	db 15, EMBER
	db 19, BELLOW
	db 23, BLITZ_STRIKE
	db 28, HEAT_RUSH
	db 31, AGILITY
	db 36, FLAMETHROWER
	db 45, DOUBLE_EDGE
	db 52, BONEMERANG
	db 59, FIRE_BLAST
	db 0

MewEvosMoves:
; Evolutions
	db 0
; Learnset
	db 10, CONFUSION
	db 20, MIMIC
	db 30, HEADBUTT
	db 40, PSYCHIC_M
	db 50, PHANTASM
	db 51, TRANSFORM
	db 55, DIZZY_PUNCH
	db 59, METRONOME
	db 63, SUBSTITUTE
	db 0

GyaradosEvosMoves:
; Evolutions
	db 0
; Learnset
	db EVOLVE_LEVEL, 30, GYARADOS
	db 15, TACKLE
	db 20, BITE
	db 25, LEER
	db 30, BELLOW
	db 35, BLOOD_RUSH
	db 40, RIPTIDE
	db 45, LEAP_ATTACK
	db 50, OUTRAGE
	db 55, DOUBLE_EDGE
	db 60, HYDRO_PUMP
	db 65, HYPER_BEAM
	db 0

ShellderEvosMoves:
; Evolutions
	db EVOLVE_ITEM, WATER_STONE, 1, CLOYSTER
	db 0
; Learnset
	db 18, POWER_BIND
	db 23, SHELL_GAME
	db 28, AURORA_BEAM
	db 32, CLAMP
	db 36, UNDERBUG
	db 45, ICE_BEAM
	db 52, VENOM_DRILL
	db 56, SPIKE_CANNON
	db 0

TentacoolEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 30, TENTACRUEL
	db 0
; Learnset
	db 7, POISON_STING
	db 13, SUPER_SOAK
	db 17, SUPERSONIC
	db 23, ACID
	db 29, POWER_BIND
	db 33, WATER_PULSE
	db 39, CONFUSE_RAY
	db 43, VENOM_LASH
	db 49, BARRIER
	db 53, SOULSTEALER
	db 59, HYDRO_PUMP
	db 0

GastlyEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 25, HAUNTER
	db 0
; Learnset
	db 21, PHANTASM
	db 24, HYPNOSIS
	db 29, EMETIC_PURGE
	db 33, CONFUSE_RAY
	db 41, MEGA_DRAIN
	db 46, DOUBLE_TEAM
	db 51, MAXIMIZE
	db 57, SOULSTEALER
	db 0

ScytherEvosMoves:
; Evolutions
	db 0
; Learnset
	db 17, WING_ATTACK
	db 19, FOCUS_ENERGY
	db 23, PIN_MISSILE
	db 25, DOUBLE_TEAM
	db 27, LEAP_ATTACK
	db 32, SWORDS_DANCE
	db 38, EXTERMINATE
	db 41, SLASH
	db 48, AIR_DRILL
	db 55, AGILITY
	db 0

StaryuEvosMoves:
; Evolutions
	db EVOLVE_ITEM, WATER_STONE, 1, STARMIE
	db 0
; Learnset
	db 14, HARDEN
	db 18, SWIFT
	db 21, WATER_PULSE
	db 27, MEGA_DRAIN
	db 31, RECOVER
	db 34, DISABLE
	db 39, BARRIER
	db 43, PSYCHIC_M
	db 48, HYDRO_PUMP
	db 0

BlastoiseEvosMoves:
; Evolutions
	db 0
; Learnset
	db 6, BUBBLE
	db 8, HARDEN
	db 11, SUPER_SOAK
	db 14, LOW_KICK
	db 18, BITE
	db 23, SHELL_GAME
	db 28, CLAMP
	db 33, DIZZY_PUNCH
	db 35, BLOOD_RUSH
	db 42, METEOR_DRIVE
	db 50, HYDRO_PUMP
	db 0

PinsirEvosMoves:
; Evolutions
	db 0
; Learnset
	db 19, HARDEN
	db 21, POWER_BIND
	db 24, MUD_BOMB
	db 27, FOCUS_ENERGY
	db 30, UNDERBUG
	db 33, SPIKE_CANNON
	db 38, EARTHQUAKE
	db 45, COMBOBREAKER
	db 49, EXTERMINATE
	db 54, STRENGTH
	db 0

TangelaEvosMoves:
; Evolutions
	db 0
; Learnset
	db 14, POISONPOWDER
	db 18, WRAP
	db 23, MEGA_DRAIN
	db 26, WATER_PULSE
	db 30, SHELL_GAME
	db 34, SPORE
	db 44, POWER_BIND
	db 49, HYDRO_PUMP
	db 54, VENOM_LASH
	db 0

NothingEvosMoves:
; Evolutions
	db 0
; Learnset
	db 0

GrowlitheEvosMoves:
; Evolutions
	db EVOLVE_ITEM, FIRE_STONE, 1, ARCANINE
	db 0
; Learnset
	db 7, BITE
	db 10, LICK
	db 15, EMBER
	db 19, BELLOW
	db 23, BLITZ_STRIKE
	db 28, HEAT_RUSH
	db 31, AGILITY
	db 36, FLAMETHROWER
	db 45, DOUBLE_EDGE
	db 52, BONEMERANG
	db 59, FIRE_BLAST
	db 0

OnixEvosMoves:
; Evolutions
	db 0
; Learnset
	db 14, WRAP
	db 18, SCREECH
	db 23, METEOR_HORN
	db 27, DIG
	db 31, BLOOD_RUSH
	db 36, CRYSTALLIZE
	db 40, ROCK_SLIDE
	db 45, EARTHQUAKE
	db 49, POWER_BIND
	db 54, AGILITY
	db 59, SPIKE_CANNON
	db 0

FearowEvosMoves:
; Evolutions
	db 0
; Learnset
	db 9, LEER
	db 13, MUD_CLAW
	db 18, WING_ATTACK
	db 22, ILL_WIND
	db 26, MOCKINGBIRD
	db 30, BLOOD_RUSH
	db 33, AIR_DRILL
	db 37, PHANTASM
	db 42, AGILITY
	db 48, DOUBLE_EDGE
	db 55, SPIKE_CANNON
	db 0

PidgeyEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 24, PIDGEOTTO
	db 0
; Learnset
	db 6, GUST
	db 9, SAND_ATTACK
	db 14, AGILITY
	db 17, SWIFT
	db 23, WING_ATTACK
	db 28, RAZOR_LEAF
	db 32, BLITZ_STRIKE
	db 35, HONE_EDGE
	db 41, HURRICANE
	db 48, SENBONZAKURA
	db 54, DOUBLE_EDGE
	db 60, MOCKINGBIRD
	db 0

SlowpokeEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 28, SLOWBRO
	db 0
; Learnset
	db 12, CONFUSION
	db 17, DISABLE
	db 20, HEADBUTT
	db 24, CLAMP
	db 29, PSYBEAM
	db 32, SHELL_GAME
	db 36, SLUDGE_BOMB
	db 41, CALM_MIND
	db 45, PSYCHIC_M
	db 0

KadabraEvosMoves:
; Evolutions
	db EVOLVE_TRADE, 1, ALAKAZAM
	db EVOLVE_LEVEL, 37, ALAKAZAM
	db 0
; Learnset
	db 16, CONFUSION
	db 20, DISABLE
	db 27, PSYBEAM
	db 31, RECOVER
	db 38, PSYCHIC_M
	db 42, REFLECT
	db 54, VOID_MIND
	db 0

GravelerEvosMoves:
; Evolutions
	db EVOLVE_TRADE, 1, GOLEM
	db EVOLVE_LEVEL, 37, GOLEM
	db 0
; Learnset
	db 11, HARDEN
	db 13, SEISMIC_TOSS
	db 16, ROCK_THROW
	db 19, BULK_UP
	db 21, BLAZE_HAMMER
	db 28, ROCK_SLIDE
	db 31, DIZZY_PUNCH
	db 34, EXPLOSION
	db 39, EARTHQUAKE
	db 46, METAMORPHIC
	db 52, PISTON_KICK
	db 60, COMBOBREAKER
	db 0

ChanseyEvosMoves:
; Evolutions
	db 0
; Learnset
	db 18, SEISMIC_TOSS
	db 23, SING
	db 28, MINIMIZE
	db 34, SHADOW_BALL
	db 41, SOFTBOILED
	db 47, EGG_BOMB
	db 54, DOUBLE_EDGE
	db 0

MachokeEvosMoves:
; Evolutions
	db EVOLVE_TRADE, 1, MACHAMP
	db EVOLVE_LEVEL, 37, MACHAMP
	db 0
; Learnset
	db 15, LOW_KICK
	db 18, SEISMIC_TOSS
	db 20, BULK_UP
	db 23, COMBOBREAKER
	db 26, FOCUS_ENERGY
	db 30, POWER_BIND
	db 35, MACH_PUNCH
	db 41, SHADOW_BOX
	db 44, LEAP_ATTACK
	db 47, SHORYUKEN
	db 52, DIZZY_PUNCH
	db 56, METEOR_DRIVE
	db 0

MrMimeEvosMoves:
; Evolutions
	db 0
; Learnset
	db 17, DOUBLESLAP
	db 19, LIGHT_SCREEN
	db 23, PSYBEAM
	db 25, TELEPORT
	db 28, MOCKINGBIRD
	db 31, SEISMIC_TOSS
	db 35, VOID_MIND
	db 39, PSYCHIC_M
	db 44, ILL_WIND
	db 48, SUBSTITUTE
	db 53, MIMIC
	db 0

HitmonleeEvosMoves:
; Evolutions
	db 0
; Learnset
	db 20, LOW_KICK
	db 24, STOMP
	db 27, FOCUS_ENERGY
	db 31, METEOR_SWEEP
	db 36, PISTON_KICK
	db 41, BLITZ_STRIKE
	db 46, METEOR_DRIVE
	db 53, HI_JUMP_KICK
	db 0

HitmonchanEvosMoves:
; Evolutions
	db 0
; Learnset
	db 19, DOUBLE_TEAM
	db 22, MACH_PUNCH
	db 24, BLAZE_HAMMER
	db 25, FROST_FIST
	db 26, ZAPPERCUT
	db 32, DIZZY_PUNCH
	db 37, SHADOW_BOX
	db 43, MIMIC
	db 49, SHORYUKEN
	db 0

ArbokEvosMoves:
; Evolutions
	db 0
; Learnset
	db 7, ABSORB
	db 13, BITE
	db 19, ACID
	db 23, HYPNOSIS
	db 29, LEECH_LIFE
	db 35, BLITZ_STRIKE
	db 39, FOCUS_ENERGY
	db 45, SOULSTEALER
	db 51, VENOM_LASH
	db 55, POWER_BIND
	db 0

ParasectEvosMoves:
; Evolutions
	db 0
; Learnset
	db 13, STUN_SPORE
	db 15, MEGA_DRAIN
	db 18, UNDERBUG
	db 21, SLASH
	db 25, PHANTASM
	db 28, SPORE
	db 33, LEECH_LIFE
	db 39, CRABHAMMER
	db 44, SOULSTEALER
	db 49, EXTERMINATE
	db 0

PsyduckEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 25, GOLDUCK
	db 0
; Learnset
	db 10, CONFUSION
	db 13, SUPER_SOAK
	db 17, DISABLE
	db 20, DOUBLESLAP
	db 23, LOW_KICK
	db 27, RIPTIDE
	db 32, METRONOME
	db 34, SWIFT
	db 38, CALM_MIND
	db 44, PSYCHIC_M
	db 50, TELEPORT
	db 56, MOCKINGBIRD
	db 60, HYDRO_PUMP
	db 0

DrowzeeEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 26, HYPNO
	db 0
; Learnset
	db 12, DISABLE
	db 17, CONFUSION
	db 24, HEADBUTT
	db 29, SMOG
	db 33, PHANTASM
	db 37, PSYCHIC_M
	db 43, TOXIC
	db 48, EMETIC_PURGE
	db 54, SOULSTEALER
	db 0

GolemEvosMoves:
; Evolutions
	db 0
; Learnset
	db 11, HARDEN
	db 13, SEISMIC_TOSS
	db 16, ROCK_THROW
	db 19, BULK_UP
	db 21, BLAZE_HAMMER
	db 28, ROCK_SLIDE
	db 31, DIZZY_PUNCH
	db 34, EXPLOSION
	db 39, EARTHQUAKE
	db 46, METAMORPHIC
	db 52, PISTON_KICK
	db 60, COMBOBREAKER
	db 0

MagmarEvosMoves:
; Evolutions
	db 0
; Learnset
	db 15, SMOG
	db 17, SMOKESCREEN
	db 20, METEOR_SWEEP
	db 22, CONFUSE_RAY
	db 24, EMETIC_PURGE
	db 27, BLAZE_HAMMER
	db 30, TELEPORT
	db 37, EGG_BOMB
	db 43, SLUDGE_BOMB
	db 49, FIRE_BLAST
	db 54, TOXIC
	db 0

ElectabuzzEvosMoves:
; Evolutions
	db 0
; Learnset
	db 26, MACH_PUNCH
	db 28, LIGHT_SCREEN
	db 30, ZAPPERCUT
	db 33, SHADOW_BOX
	db 37, SEISMIC_TOSS
	db 42, DIZZY_PUNCH
	db 47, THUNDER
	db 54, HYPER_BEAM
	db 0

MagnetonEvosMoves:
; Evolutions
	db 0
; Learnset
	db 13, THUNDERSHOCK
	db 16, SUPERSONIC
	db 19, SPARK
	db 22, THUNDER_WAVE
	db 26, ILL_WIND
	db 31, TELEPORT
	db 34, THUNDERBOLT
	db 38, TRI_ATTACK
	db 43, CONVERSION
	db 47, THUNDER
	db 52, SUPERNOVA
	db 0

KoffingEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 27, WEEZING
	db 0
; Learnset
	db 10, HEADBUTT
	db 14, SMOKESCREEN
	db 18, ACID
	db 21, DISABLE
	db 25, BODY_SLAM
	db 29, EMETIC_PURGE
	db 33, TOXIC
	db 38, EGG_BOMB
	db 43, ADAPTATION
	db 47, SLUDGE_BOMB
	db 52, EXPLOSION
	db 0

MankeyEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 27, PRIMEAPE
	db 0
; Learnset
	db 9, DEMOLISH
	db 12, MUD_CLAW
	db 15, SCREECH
	db 18, FOCUS_ENERGY
	db 20, LOW_KICK
	db 23, SEISMIC_TOSS
	db 25, BLOOD_RUSH
	db 27, ILL_WIND
	db 35, UNDERBUG
	db 39, MACH_PUNCH
	db 45, SHADOW_BOX
	db 51, OUTRAGE
	db 54, COMBOBREAKER
	db 0

SeelEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 27, DEWGONG
	db 0
; Learnset
	db 16, HEADBUTT
	db 21, AURORA_BEAM
	db 24, WATER_PULSE
	db 26, VENOM_LASH
	db 30, REST
	db 32, BODY_SLAM
	db 35, ICE_BEAM
	db 39, METEOR_DRIVE
	db 41, AURORA_MIST
	db 43, CALM_MIND
	db 50, BLIZZARD
	db 55, SWIFT
	db 59, SHELL_GAME
	db 0

DiglettEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 26, DUGTRIO
	db 0
; Learnset
	db 13, MUD_CLAW
	db 15, GROWL
	db 19, DIG
	db 24, ROCK_THROW
	db 30, MUD_BOMB
	db 35, SLASH
	db 39, DISABLE
	db 43, EARTHQUAKE
	db 49, ROCK_SLIDE
	db 54, AGILITY
	db 59, CLAY_ARMOR
	db 0

TaurosEvosMoves:
; Evolutions
	db 0
; Learnset
	db 19, STOMP
	db 24, BLOOD_RUSH
	db 29, MUD_BOMB
	db 33, BODY_SLAM
	db 37, SWORDS_DANCE
	db 42, METEOR_DRIVE
	db 48, PISTON_KICK
	db 53, HYPER_BEAM
	db 0

FarfetchdEvosMoves:
; Evolutions
	db 0
; Learnset
	db 15, WING_ATTACK
	db 17, AGILITY
	db 19, SOFTBOILED
	db 22, RAZOR_LEAF
	db 24, FLY
	db 27, SWIFT
	db 31, SWORDS_DANCE
	db 35, SENBONZAKURA
	db 40, BRAVE_BIRD
	db 45, MOCKINGBIRD
	db 0

VenonatEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 23, VENOMOTH
	db 0
; Learnset
	db 7, ABSORB
	db 10, POISONPOWDER
	db 13, PIN_MISSILE
	db 15, STUN_SPORE
	db 16, SLEEP_POWDER
	db 18, LEECH_LIFE
	db 22, PSYBEAM
	db 30, AGILITY
	db 33, SLUDGE_BOMB
	db 37, SOULSTEALER
	db 37, SLEEP_POWDER
	db 42, PSYCHIC_M
	db 0

DragoniteEvosMoves:
; Evolutions
	db 0
; Learnset
	db 25, RIPTIDE
	db 29, AURORA_MIST
	db 33, TWISTER
	db 38, BLITZ_STRIKE
	db 46, AGILITY
	db 47, HURRICANE
	db 52, HYPER_BEAM
	db 60, OUTRAGE
	db 0

DoduoEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 25, DODRIO
	db 0
; Learnset
	db 10, DOUBLE_KICK
	db 14, STOMP
	db 17, WING_ATTACK
	db 20, MUD_BOMB
	db 23, BLOOD_RUSH
	db 26, AGILITY
	db 30, AIR_DRILL
	db 35, MOCKINGBIRD
	db 41, PISTON_KICK
	db 49, TWINEEDLE
	db 0

PoliwagEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 23, POLIWHIRL
	db 0
; Learnset
	db 12, SUPER_SOAK
	db 15, HYPNOSIS
	db 19, CONFUSION
	db 22, WATER_PULSE
	db 27, BODY_SLAM
	db 30, RIPTIDE
	db 36, DIZZY_PUNCH
	db 41, CALM_MIND
	db 45, HYDRO_PUMP
	db 52, SHADOW_BOX
	db 0

JynxEvosMoves:
; Evolutions
	db 0
; Learnset
	db 21, AURORA_BEAM
	db 23, LICK
	db 27, BODY_SLAM
	db 30, FROST_FIST
	db 34, PSYBEAM
	db 39, CALM_MIND
	db 42, SOULSTEALER
	db 42, LOVELY_KISS
	db 47, BLIZZARD
	db 54, EGG_BOMB
	db 0

MoltresEvosMoves:
; Evolutions
	db 0
; Learnset
	db 51, BRAVE_BIRD
	db 55, SOFTBOILED
	db 60, FIRE_BLAST
	db 65, AGILITY
	db 70, PHOENIX_DIVE
	db 0

ArticunoEvosMoves:
; Evolutions
	db 0
; Learnset
	db 51, HURRICANE
	db 55, SHELL_GAME
	db 60, BLIZZARD
	db 65, AGILITY
	db 70, WINTER_GALE
	db 0

ZapdosEvosMoves:
; Evolutions
	db 0
; Learnset
	db 51, AIR_DRILL
	db 55, BLOOD_RUSH
	db 60, THUNDER
	db 65, AGILITY
	db 70, STORM_DRILL
	db 0

DittoEvosMoves:
; Evolutions
	db 0
; Learnset
	db 0

MeowthEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 22, PERSIAN
	db 0
; Learnset
	db 8, LICK
	db 10, MUD_CLAW
	db 12, BITE
	db 15, DOUBLE_KICK
	db 17, SCREECH
	db 21, SWIFT
	db 25, LEAP_ATTACK
	db 33, AGILITY
	db 45, METEOR_DRIVE
	db 53, SLASH
	db 0

KrabbyEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 29, KINGLER
	db 0
; Learnset
	db 14, MUD_CLAW
	db 17, AGILITY
	db 19, SUPER_SOAK
	db 22, UNDERBUG
	db 26, MUD_BOMB
	db 30, SLASH
	db 35, CRABHAMMER
	db 39, EXTERMINATE
	db 44, EARTHQUAKE
	db 50, SPIKE_CANNON
	db 0

VulpixEvosMoves:
; Evolutions
	db EVOLVE_ITEM, FIRE_STONE, 1, NINETALES
	db 0
; Learnset
	db 9, LICK
	db 12, DISABLE
	db 16, BITE
	db 21, MIRAGE
	db 23, CONFUSE_RAY
	db 28, PHANTASM
	db 35, FLAMETHROWER
	db 44, HYPNOSIS
	db 50, PSYCHIC_M
	db 56, SOULSTEALER
	db 60, FIRE_SPIN
	db 0

NinetalesEvosMoves:
; Evolutions
	db 0
; Learnset
	db 9, LICK
	db 12, DISABLE
	db 16, BITE
	db 21, MIRAGE
	db 23, CONFUSE_RAY
	db 28, PHANTASM
	db 35, FLAMETHROWER
	db 44, HYPNOSIS
	db 50, PSYCHIC_M
	db 56, SOULSTEALER
	db 60, FIRE_SPIN
	db 0

PikachuEvosMoves:
; Evolutions
	db EVOLVE_ITEM, THUNDER_STONE, 1, RAICHU
	db 0
; Learnset
	db 6, TACKLE
	db 9, THUNDER_WAVE
	db 12, SPARK
	db 16, AGILITY
	db 22, SWIFT
	db 26, THUNDERBOLT
	db 31, FOCUS_ENERGY
	db 36, BLITZ_STRIKE
	db 45, THUNDER
	db 52, HYPER_BEAM
	db 0

RaichuEvosMoves:
; Evolutions
	db 0
; Learnset
	db 6, TACKLE
	db 9, THUNDER_WAVE
	db 12, SPARK
	db 16, AGILITY
	db 22, SWIFT
	db 26, THUNDERBOLT
	db 31, FOCUS_ENERGY
	db 36, BLITZ_STRIKE
	db 45, THUNDER
	db 52, HYPER_BEAM
	db 0

DratiniEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 30, DRAGONAIR
	db 0
; Learnset
	db 20, THUNDER_WAVE
	db 25, RIPTIDE
	db 29, AURORA_MIST
	db 33, TWISTER
	db 38, BLITZ_STRIKE
	db 46, AGILITY
	db 52, HYPER_BEAM
	db 60, OUTRAGE
	db 0

DragonairEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 46, DRAGONITE
	db 0
; Learnset
	db 0

KabutoEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 33, KABUTOPS
	db 0
; Learnset
	db 24, LEECH_LIFE
	db 28, POWER_BIND
	db 35, MUD_BOMB
	db 39, METEOR_DRIVE
	db 44, EXTERMINATE
	db 49, EARTHQUAKE
	db 53, METAMORPHIC
	db 0

KabutopsEvosMoves:
; Evolutions
	db 0
; Learnset
	db 24, LEECH_LIFE
	db 28, POWER_BIND
	db 33, HONE_EDGE
	db 35, MUD_BOMB
	db 39, METEOR_DRIVE
	db 44, EXTERMINATE
	db 49, EARTHQUAKE
	db 53, METAMORPHIC
	db 0

HorseaEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 27, SEADRA
	db 0
; Learnset
	db 14, SUPER_SOAK
	db 17, SMOKESCREEN
	db 21, GUST
	db 24, WATER_PULSE
	db 26, AGILITY
	db 31, TWISTER
	db 35, RIPTIDE
	db 39, DOUBLE_TEAM
	db 44, WYRM_WRATH
	db 49, HYDRO_PUMP
	db 0

SeadraEvosMoves:
; Evolutions
	db 0
; Learnset
	db 14, SUPER_SOAK
	db 17, SMOKESCREEN
	db 21, GUST
	db 24, WATER_PULSE
	db 26, AGILITY
	db 31, TWISTER
	db 35, RIPTIDE
	db 39, DOUBLE_TEAM
	db 44, WYRM_WRATH
	db 49, HYDRO_PUMP
	db 0

WinterDragonairEvosMoves:
; Evolutions
	db 0
; Learnset
	db 20, THUNDER_WAVE
	db 25, RIPTIDE
	db 29, AURORA_MIST
	db 33, TWISTER
	db 38, BLITZ_STRIKE
	db 46, AGILITY
	db 52, HYPER_BEAM
	db 60, OUTRAGE
	db 0

SandshrewEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 23, SANDSLASH
	db 0
; Learnset
	db 10, MUD_CLAW
	db 12, SAND_ATTACK
	db 14, PIN_MISSILE
	db 17, ROCK_ON
	db 20, DIG
	db 24, SWIFT
	db 29, TWINEEDLE
	db 35, AGILITY
	db 43, EARTHQUAKE
	db 51, SLASH
	db 0

SandslashEvosMoves:
; Evolutions
	db 0
; Learnset
	db 10, MUD_CLAW
	db 12, SAND_ATTACK
	db 14, PIN_MISSILE
	db 17, ROCK_ON
	db 20, DIG
	db 24, SWIFT
	db 29, TWINEEDLE
	db 35, AGILITY
	db 43, EARTHQUAKE
	db 51, SLASH
	db 0

OmanyteEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 33, OMASTAR
	db 0
; Learnset
	db 24, MEGA_DRAIN
	db 28, SHELL_GAME
	db 30, CLAMP
	db 35, SPIKE_CANNON
	db 39, BODY_SLAM
	db 43, ROCK_ON
	db 48, HYDRO_PUMP
	db 0

OmastarEvosMoves:
; Evolutions
	db 0
; Learnset
	db 24, MEGA_DRAIN
	db 28, SHELL_GAME
	db 30, CLAMP
	db 35, SPIKE_CANNON
	db 39, BODY_SLAM
	db 43, ROCK_ON
	db 48, HYDRO_PUMP
	db 0

JigglypuffEvosMoves:
; Evolutions
	db EVOLVE_ITEM, MOON_STONE, 1, WIGGLYTUFF
	db 0
; Learnset
	db 9, DISABLE
	db 13, ROCK_ON
	db 16, DOUBLESLAP
	db 24, BODY_SLAM
	db 32, MINIMIZE
	db 37, DIZZY_PUNCH
	db 42, DOUBLE_EDGE
	db 50, MAXIMIZE
	db 55, SOULSTEALER
	db 60, EXPLOSION
	db 0

WigglytuffEvosMoves:
; Evolutions
	db 0
; Learnset
	db 9, DISABLE
	db 13, ROCK_ON
	db 16, DOUBLESLAP
	db 24, BODY_SLAM
	db 32, MINIMIZE
	db 37, DIZZY_PUNCH
	db 42, DOUBLE_EDGE
	db 50, MAXIMIZE
	db 55, SOULSTEALER
	db 60, EXPLOSION
	db 0

EeveeEvosMoves:
; Evolutions
	db EVOLVE_ITEM, FIRE_STONE, 1, FLAREON
	db EVOLVE_ITEM, THUNDER_STONE, 1, JOLTEON
	db EVOLVE_ITEM, WATER_STONE, 1, VAPOREON
	db 0
; Learnset
	db 6, HONE_EDGE
	db 10, BITE
	db 14, BELLOW
	db 18, SWIFT
	db 25, HEADBUTT
	db 30, TRI_ATTACK
	db 0

FlareonEvosMoves:
; Evolutions
	db 0
; Learnset
	db 6, HONE_EDGE
	db 10, BITE
	db 14, BELLOW
	db 18, SWIFT
	db 21, BLOOD_RUSH
	db 25, AGILITY
	db 28, FLAMETHROWER
	db 32, TRI_ATTACK
	db 38, PISTON_KICK
	db 44, BLITZ_STRIKE
	db 49, FIRE_BLAST
	db EVO_MOVE_LEVEL, EMBER
	db 0

JolteonEvosMoves:
; Evolutions
	db 0
; Learnset
	db 6, HONE_EDGE
	db 10, BITE
	db 14, BELLOW
	db 18, SWIFT
	db 21, THUNDER_WAVE
	db 25, AGILITY
	db 28, THUNDERBOLT
	db 32, TRI_ATTACK
	db 38, PIN_MISSILE
	db 44, PHANTASM
	db 49, THUNDER
	db EVO_MOVE_LEVEL, THUNDERSHOCK
	db 0

VaporeonEvosMoves:
; Evolutions
	db 0
; Learnset
	db 6, HONE_EDGE
	db 10, BITE
	db 14, BELLOW
	db 18, SWIFT
	db 21, WATER_PULSE
	db 25, BARRIER
	db 28, RIPTIDE
	db 32, TRI_ATTACK
	db 35, SLUDGE_BOMB
	db 44, AURORA_MIST
	db 49, HYDRO_PUMP
	db EVO_MOVE_LEVEL, SUPER_SOAK
	db 0

MachopEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 28, MACHOKE
	db 0
; Learnset
	db 15, LOW_KICK
	db 18, SEISMIC_TOSS
	db 20, BULK_UP
	db 23, COMBOBREAKER
	db 26, FOCUS_ENERGY
	db 30, POWER_BIND
	db 35, MACH_PUNCH
	db 41, SHADOW_BOX
	db 44, LEAP_ATTACK
	db 47, SHORYUKEN
	db 52, DIZZY_PUNCH
	db 56, METEOR_DRIVE
	db 0

ZubatEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 22, GOLBAT
	db 0
; Learnset
	db 10, SUPERSONIC
	db 15, LEECH_LIFE
	db 18, BITE
	db 21, WING_ATTACK
	db 25, CONFUSE_RAY
	db 28, ILL_WIND
	db 30, HYPER_FANG
	db 37, AIR_DRILL
	db 44, SOULSTEALER
	db 50, MAXIMIZE
	db 55, VENOM_DRILL
	db 0

EkansEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 22, ARBOK
	db 0
; Learnset
	db 7, ABSORB
	db 13, BITE
	db 19, ACID
	db 23, HYPNOSIS
	db 29, LEECH_LIFE
	db 35, BLITZ_STRIKE
	db 39, FOCUS_ENERGY
	db 45, SOULSTEALER
	db 51, VENOM_LASH
	db 55, POWER_BIND
	db 0

ParasEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 24, PARASECT
	db 0
; Learnset
	db 13, STUN_SPORE
	db 15, MEGA_DRAIN
	db 18, UNDERBUG
	db 21, SLASH
	db 25, PHANTASM
	db 28, SPORE
	db 33, LEECH_LIFE
	db 39, CRABHAMMER
	db 44, SOULSTEALER
	db 49, EXTERMINATE
	db 0

PoliwhirlEvosMoves:
; Evolutions
	db EVOLVE_ITEM, WATER_STONE, 1, POLIWRATH
	db 0
; Learnset
	db 12, SUPER_SOAK
	db 15, HYPNOSIS
	db 19, CONFUSION
	db 22, WATER_PULSE
	db 27, BODY_SLAM
	db 30, RIPTIDE
	db 36, DIZZY_PUNCH
	db 41, CALM_MIND
	db 45, HYDRO_PUMP
	db 52, SHADOW_BOX
	db 0

PoliwrathEvosMoves:
; Evolutions
	db 0
; Learnset
	db 12, SUPER_SOAK
	db 15, HYPNOSIS
	db 19, CONFUSION
	db 22, WATER_PULSE
	db 27, BODY_SLAM
	db 30, RIPTIDE
	db 36, DIZZY_PUNCH
	db 41, CALM_MIND
	db 45, HYDRO_PUMP
	db 52, SHADOW_BOX
	db 0

WeedleEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 7, KAKUNA
	db 0
; Learnset
	db 0

KakunaEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 10, BEEDRILL
	db 0
; Learnset
	db 7, HARDEN
	db 7, ACID
	db 15, CRYSTALLIZE
	db 0

BeedrillEvosMoves:
; Evolutions
	db 0
; Learnset
	db 10, PIN_MISSILE
	db 10, SUPERSONIC
	db 14, FOCUS_ENERGY
	db 17, ILL_WIND
	db 22, BLOOD_RUSH
	db 25, OUTRAGE
	db 30, AGILITY
	db 35, TWINEEDLE
	db 40, AIR_DRILL
	db 47, VENOM_DRILL
	db 50, CRYSTALLIZE
	db 0

DodrioEvosMoves:
; Evolutions
	db 0
; Learnset
	db 10, DOUBLE_KICK
	db 14, STOMP
	db 17, WING_ATTACK
	db 20, MUD_BOMB
	db 23, BLOOD_RUSH
	db 26, AGILITY
	db 30, AIR_DRILL
	db 35, MOCKINGBIRD
	db 41, PISTON_KICK
	db 49, TWINEEDLE
	db 0

PrimeapeEvosMoves:
; Evolutions
	db 0
; Learnset
	db 9, DEMOLISH
	db 12, MUD_CLAW
	db 15, SCREECH
	db 18, FOCUS_ENERGY
	db 20, LOW_KICK
	db 23, SEISMIC_TOSS
	db 25, BLOOD_RUSH
	db 27, ILL_WIND
	db 35, UNDERBUG
	db 39, MACH_PUNCH
	db 45, SHADOW_BOX
	db 51, OUTRAGE
	db 54, COMBOBREAKER
	db 0

DugtrioEvosMoves:
; Evolutions
	db 0
; Learnset
	db 13, MUD_CLAW
	db 15, GROWL
	db 19, DIG
	db 24, ROCK_THROW
	db 30, MUD_BOMB
	db 35, SLASH
	db 39, DISABLE
	db 43, EARTHQUAKE
	db 49, ROCK_SLIDE
	db 54, AGILITY
	db 59, CLAY_ARMOR
	db 0

VenomothEvosMoves:
; Evolutions
	db 0
; Learnset
	db 7, ABSORB
	db 10, POISONPOWDER
	db 13, PIN_MISSILE
	db 15, STUN_SPORE
	db 16, SLEEP_POWDER
	db 18, LEECH_LIFE
	db 22, PSYBEAM
	db 27, WING_ATTACK
	db 30, AGILITY
	db 33, SLUDGE_BOMB
	db 37, SOULSTEALER
	db 37, SLEEP_POWDER
	db 42, PSYCHIC_M
	db 53, HURRICANE
	db 0

DewgongEvosMoves:
; Evolutions
	db 0
; Learnset
	db 16, HEADBUTT
	db 21, AURORA_BEAM
	db 24, WATER_PULSE
	db 26, VENOM_LASH
	db 30, REST
	db 32, BODY_SLAM
	db 35, ICE_BEAM
	db 39, METEOR_DRIVE
	db 41, AURORA_MIST
	db 43, CALM_MIND
	db 50, BLIZZARD
	db 55, SWIFT
	db 59, SHELL_GAME
	db 0

CaterpieEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 7, METAPOD
	db 0
; Learnset
	db 0

MetapodEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 10, BUTTERFREE
	db 0
; Learnset
	db 7, HARDEN
	db 7, CALM_MIND
	db 15, CRYSTALLIZE
	db 0

ButterfreeEvosMoves:
; Evolutions
	db 0
; Learnset
	db 10, CONFUSION
	db 12, GUST
	db 15, POISONPOWDER
	db 16, DISABLE
	db 17, PSYBEAM
	db 20, CONFUSE_RAY
	db 24, STUN_SPORE
	db 27, HURRICANE
	db 33, PSYCHIC_M
	db 35, EMETIC_PURGE
	db 45, SOULSTEALER
	db 45, SLEEP_POWDER
	db 50, CRYSTALLIZE
	db 0

MachampEvosMoves:
; Evolutions
	db 0
; Learnset
	db 15, LOW_KICK
	db 18, SEISMIC_TOSS
	db 20, BULK_UP
	db 23, COMBOBREAKER
	db 26, FOCUS_ENERGY
	db 30, POWER_BIND
	db 35, MACH_PUNCH
	db 41, SHADOW_BOX
	db 44, LEAP_ATTACK
	db 47, SHORYUKEN
	db 52, DIZZY_PUNCH
	db 56, METEOR_DRIVE
	db 0

GolduckEvosMoves:
; Evolutions
	db 0
; Learnset
	db 10, CONFUSION
	db 13, SUPER_SOAK
	db 17, DISABLE
	db 20, DOUBLESLAP
	db 23, LOW_KICK
	db 27, RIPTIDE
	db 32, METRONOME
	db 34, SWIFT
	db 38, CALM_MIND
	db 44, PSYCHIC_M
	db 50, TELEPORT
	db 56, MOCKINGBIRD
	db 60, HYDRO_PUMP
	db 0

HypnoEvosMoves:
; Evolutions
	db 0
; Learnset
	db 12, DISABLE
	db 17, CONFUSION
	db 24, HEADBUTT
	db 29, SMOG
	db 33, PHANTASM
	db 37, PSYCHIC_M
	db 43, TOXIC
	db 48, EMETIC_PURGE
	db 54, SOULSTEALER
	db 0

GolbatEvosMoves:
; Evolutions
	db 0
; Learnset
	db 10, SUPERSONIC
	db 15, LEECH_LIFE
	db 18, BITE
	db 21, WING_ATTACK
	db 25, CONFUSE_RAY
	db 28, ILL_WIND
	db 30, HYPER_FANG
	db 37, AIR_DRILL
	db 44, SOULSTEALER
	db 50, MAXIMIZE
	db 55, VENOM_DRILL
	db 0

MewtwoEvosMoves:
; Evolutions
	db 0
; Learnset
	db 66, PSYCHIC_M
	db 70, RECOVER
	db 72, BARRIER
	db 75, AURORA_MIST
	db 81, CALM_MIND
	db 0

SnorlaxEvosMoves:
; Evolutions
	db 0
; Learnset
	db 35, BODY_SLAM
	db 41, EMETIC_PURGE
	db 46, ROCK_SLIDE
	db 51, DOUBLE_EDGE
	db 55, PISTON_KICK
	db 59, EXPLOSION
	db 0

MagikarpEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 30, GYARADOS
	db 15, TACKLE
	db 20, BITE
	db 25, LEER
	db 0
; Learnset
	db 0

MukEvosMoves:
; Evolutions
	db 0
; Learnset
	db 14, ACID
	db 23, HARDEN
	db 26, MUD_BOMB
	db 29, MINIMIZE
	db 33, BODY_SLAM
	db 37, SLUDGE_BOMB
	db 41, RECOVER
	db 46, MAXIMIZE
	db 50, DOUBLE_EDGE
	db 55, VENOM_LASH
	db 0

KinglerEvosMoves:
; Evolutions
	db 0
; Learnset
	db 14, MUD_CLAW
	db 17, AGILITY
	db 19, SUPER_SOAK
	db 22, UNDERBUG
	db 26, MUD_BOMB
	db 30, SLASH
	db 35, CRABHAMMER
	db 39, EXTERMINATE
	db 44, EARTHQUAKE
	db 50, SPIKE_CANNON
	db 0

CloysterEvosMoves:
; Evolutions
	db 0
; Learnset
	db 18, POWER_BIND
	db 23, SHELL_GAME
	db 28, AURORA_BEAM
	db 32, CLAMP
	db 36, UNDERBUG
	db 45, ICE_BEAM
	db 52, VENOM_DRILL
	db 56, SPIKE_CANNON
	db 0

ElectrodeEvosMoves:
; Evolutions
	db 0
; Learnset
	db 15, THUNDER_WAVE
	db 18, SPARK
	db 22, SWIFT
	db 24, HEAT_RUSH
	db 28, SCREECH
	db 31, THUNDERBOLT
	db 35, EGG_BOMB
	db 39, SUPERNOVA
	db 42, EXPLOSION
	db 48, THUNDER
	db 0

ClefableEvosMoves:
; Evolutions
	db 0
; Learnset
	db 13, SING
	db 15, DOUBLESLAP
	db 17, METRONOME
	db 21, PSYBEAM
	db 25, LIGHT_SCREEN
	db 28, MIMIC
	db 33, LOVELY_KISS
	db 38, PSYCHIC_M
	db 45, AURORA_MIST
	db 54, SENBONZAKURA
	db 59, TRI_ATTACK
	db 65, MINIMIZE
	db 0

WeezingEvosMoves:
; Evolutions
	db 0
; Learnset
	db 10, HEADBUTT
	db 14, SMOKESCREEN
	db 18, ACID
	db 21, DISABLE
	db 25, BODY_SLAM
	db 29, EMETIC_PURGE
	db 33, TOXIC
	db 38, EGG_BOMB
	db 43, ADAPTATION
	db 47, SLUDGE_BOMB
	db 52, EXPLOSION
	db 0

PersianEvosMoves:
; Evolutions
	db 0
; Learnset
	db 8, LICK
	db 10, MUD_CLAW
	db 12, BITE
	db 15, DOUBLE_KICK
	db 17, SCREECH
	db 21, SWIFT
	db 25, LEAP_ATTACK
	db 33, AGILITY
	db 45, METEOR_DRIVE
	db 53, SLASH
	db 0

MarowakEvosMoves:
; Evolutions
	db 0
; Learnset
	db 14, FOCUS_ENERGY
	db 18, SCREECH
	db 22, LIGHT_SCREEN
	db 25, PHANTASM
	db 27, HEADBUTT
	db 30, DIG
	db 33, MACH_PUNCH
	db 36, SHADOW_BOX
	db 40, BONEMERANG
	db 45, METEOR_DRIVE
	db 50, COMBOBREAKER
	db 0

HaunterEvosMoves:
; Evolutions
	db EVOLVE_TRADE, 1, GENGAR
	db EVOLVE_LEVEL, 37, GENGAR
	db 0
; Learnset
	db 21, PHANTASM
	db 24, HYPNOSIS
	db 29, EMETIC_PURGE
	db 33, CONFUSE_RAY
	db 41, SHADOW_BOX
	db 46, DOUBLE_TEAM
	db 51, MAXIMIZE
	db 57, SOULSTEALER
	db 0

AbraEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 16, KADABRA
	db 0
; Learnset
	db 0

AlakazamEvosMoves:
; Evolutions
	db 0
; Learnset
	db 16, CONFUSION
	db 20, DISABLE
	db 27, PSYBEAM
	db 31, RECOVER
	db 38, PSYCHIC_M
	db 42, REFLECT
	db 54, VOID_MIND
	db 0

PidgeottoEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 48, PIDGEOT
	db 0
; Learnset
	db 6, GUST
	db 9, SAND_ATTACK
	db 14, AGILITY
	db 17, SWIFT
	db 23, WING_ATTACK
	db 28, RAZOR_LEAF
	db 32, BLITZ_STRIKE
	db 35, HONE_EDGE
	db 41, HURRICANE
	db 48, SENBONZAKURA
	db 54, DOUBLE_EDGE
	db 60, MOCKINGBIRD
	db 0

PidgeotEvosMoves:
; Evolutions
	db 0
; Learnset
	db 6, GUST
	db 9, SAND_ATTACK
	db 14, AGILITY
	db 17, SWIFT
	db 23, WING_ATTACK
	db 28, RAZOR_LEAF
	db 32, BLITZ_STRIKE
	db 35, HONE_EDGE
	db 41, HURRICANE
	db 48, SENBONZAKURA
	db 54, DOUBLE_EDGE
	db 60, MOCKINGBIRD
	db 0

StarmieEvosMoves:
; Evolutions
	db 0
; Learnset
	db 14, HARDEN
	db 18, SWIFT
	db 21, WATER_PULSE
	db 27, MEGA_DRAIN
	db 31, RECOVER
	db 34, DISABLE
	db 39, BARRIER
	db 43, PSYCHIC_M
	db 48, HYDRO_PUMP
	db 0

BulbasaurEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 16, IVYSAUR
	db 0
; Learnset
	db 6, LEECH_SEED
	db 8, VINE_WHIP
	db 11, POISONPOWDER
	db 14, ADAPTATION
	db 18, STUN_SPORE
	db 21, RAZOR_LEAF
	db 25, EMETIC_PURGE
	db 33, SLEEP_POWDER
	db 38, VENOM_LASH
	db 45, SENBONZAKURA
	db 52, TOXIC
	db 0

VenusaurEvosMoves:
; Evolutions
	db 0
; Learnset
	db 6, LEECH_SEED
	db 8, VINE_WHIP
	db 11, POISONPOWDER
	db 14, ADAPTATION
	db 18, STUN_SPORE
	db 21, RAZOR_LEAF
	db 25, EMETIC_PURGE
	db 33, SLEEP_POWDER
	db 38, VENOM_LASH
	db 45, SENBONZAKURA
	db 52, TOXIC
	db 0

TentacruelEvosMoves:
; Evolutions
	db 0
; Learnset
	db 7, POISON_STING
	db 13, SUPER_SOAK
	db 17, SUPERSONIC
	db 23, ACID
	db 29, POWER_BIND
	db 33, WATER_PULSE
	db 39, CONFUSE_RAY
	db 43, VENOM_LASH
	db 49, BARRIER
	db 53, SOULSTEALER
	db 59, HYDRO_PUMP
	db 0

GoldeenEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 25, SEAKING
	db 0
; Learnset
	db 15, SUPERSONIC
	db 18, WATER_PULSE
	db 21, HEADBUTT
	db 24, MUD_BOMB
	db 27, AIR_DRILL
	db 31, RIPTIDE
	db 35, AGILITY
	db 38, METEOR_DRIVE
	db 43, DOUBLE_EDGE
	db 45, HYDRO_PUMP
	db 0

SeakingEvosMoves:
; Evolutions
	db 0
; Learnset
	db 15, SUPERSONIC
	db 18, WATER_PULSE
	db 21, HEADBUTT
	db 24, MUD_BOMB
	db 27, AIR_DRILL
	db 31, RIPTIDE
	db 35, AGILITY
	db 38, METEOR_DRIVE
	db 43, DOUBLE_EDGE
	db 45, HYDRO_PUMP
	db 0

PonytaEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 30, RAPIDASH
	db 0
; Learnset
	db 9, CONFUSION
	db 18, HEAT_RUSH
	db 21, DOUBLE_KICK
	db 25, FOCUS_ENERGY
	db 28, PSYBEAM
	db 33, FIRE_SPIN
	db 36, PISTON_KICK
	db 39, PSYCHIC_M
	db 45, DOUBLE_EDGE
	db 49, FIRE_BLAST
	db 54, METEOR_DRIVE
	db 0

RapidashEvosMoves:
; Evolutions
	db 0
; Learnset
	db 9, CONFUSION
	db 18, HEAT_RUSH
	db 21, DOUBLE_KICK
	db 25, FOCUS_ENERGY
	db 28, PSYBEAM
	db 33, FIRE_SPIN
	db 36, PISTON_KICK
	db 39, PSYCHIC_M
	db 40, AIR_DRILL
	db 45, DOUBLE_EDGE
	db 49, FIRE_BLAST
	db 54, METEOR_DRIVE
	db 0

RattataEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 20, RATICATE
	db 0
; Learnset
	db 7, BITE
	db 12, DISABLE
	db 14, MUD_BOMB
	db 17, BLITZ_STRIKE
	db 20, SCREECH
	db 23, DIG
	db 26, LEAP_ATTACK
	db 31, HYPER_FANG
	db 34, FOCUS_ENERGY
	db 40, ADAPTATION
	db 45, SUPER_FANG
	db 0

RaticateEvosMoves:
; Evolutions
	db 0
; Learnset
	db 7, BITE
	db 12, DISABLE
	db 14, MUD_BOMB
	db 17, BLITZ_STRIKE
	db 20, SCREECH
	db 23, DIG
	db 26, LEAP_ATTACK
	db 31, HYPER_FANG
	db 34, FOCUS_ENERGY
	db 40, ADAPTATION
	db 45, SUPER_FANG
	db 0

NidorinoEvosMoves:
; Evolutions
	db EVOLVE_ITEM, MOON_STONE, 1, NIDOKING
	db 0
; Learnset
	db 8, POISON_STING
	db 12, DOUBLE_KICK
	db 16, SAND_ATTACK
	db 20, MUD_BOMB
	db 25, METEOR_HORN
	db 30, STOMP
	db 35, FOCUS_ENERGY
	db 40, EARTHQUAKE
	db 46, REST
	db 52, VENOM_DRILL
	db 58, PISTON_KICK
	db 0

NidorinaEvosMoves:
; Evolutions
	db EVOLVE_ITEM, MOON_STONE, 1, NIDOQUEEN
	db 0
; Learnset
	db 8, POISON_STING
	db 12, MUD_BOMB
	db 16, SAND_ATTACK
	db 20, BULK_UP
	db 25, BLOOD_RUSH
	db 30, BODY_SLAM
	db 35, BARRIER
	db 40, EARTHQUAKE
	db 46, REST
	db 52, SLUDGE_BOMB
	db 58, METEOR_DRIVE
	db 0

GeodudeEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 24, GRAVELER
	db 0
; Learnset
	db 11, HARDEN
	db 13, SEISMIC_TOSS
	db 16, ROCK_THROW
	db 19, BULK_UP
	db 21, BLAZE_HAMMER
	db 28, ROCK_SLIDE
	db 31, DIZZY_PUNCH
	db 34, EXPLOSION
	db 39, EARTHQUAKE
	db 46, METAMORPHIC
	db 52, PISTON_KICK
	db 60, COMBOBREAKER
	db 0

PorygonEvosMoves:
; Evolutions
	db 0
; Learnset
	db 23, ILL_WIND
	db 25, CONVERSION
	db 28, RECOVER
	db 35, TRI_ATTACK
	db 42, PHANTASM
	db 49, AGILITY
	db 56, HYPER_BEAM
	db 0

AerodactylEvosMoves:
; Evolutions
	db 0
; Learnset
	db 26, ROCK_THROW
	db 32, SWORDS_DANCE
	db 38, METEOR_DRIVE
	db 44, EARTHQUAKE
	db 49, HURRICANE
	db 0

MagnemiteEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 30, MAGNETON
	db 0
; Learnset
	db 13, THUNDERSHOCK
	db 16, SUPERSONIC
	db 19, SPARK
	db 22, THUNDER_WAVE
	db 26, ILL_WIND
	db 31, TELEPORT
	db 34, THUNDERBOLT
	db 38, TRI_ATTACK
	db 43, CONVERSION
	db 47, THUNDER
	db 52, SUPERNOVA
	db 0

CharmanderEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 6, CHARMELEON
	db EVOLVE_LEVEL, 16, CHARMELEON
	db 0
; Learnset
	db 6, SMOKESCREEN
	db 9, EMBER
	db 12, SEISMIC_TOSS
	db 15, BELLOW
	db 18, HEAT_RUSH
	db 23, HONE_EDGE
	db 26, SLASH
	db 30, SHORYUKEN
	db 38, FLAMETHROWER
	db 46, HYPER_BEAM
	db 54, WYRM_WRATH
	db 60, FIRE_BLAST
	db 0

SquirtleEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 16, WARTORTLE
	db 0
; Learnset
	db 6, BUBBLE
	db 8, HARDEN
	db 11, SUPER_SOAK
	db 14, LOW_KICK
	db 18, BITE
	db 23, SHELL_GAME
	db 28, CLAMP
	db 33, DIZZY_PUNCH
	db 35, BLOOD_RUSH
	db 42, METEOR_DRIVE
	db 50, HYDRO_PUMP
	db 0

CharmeleonEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 36, CHARIZARD
	db 0
; Learnset
	db 6, SMOKESCREEN
	db 9, EMBER
	db 12, SEISMIC_TOSS
	db 15, BELLOW
	db 18, HEAT_RUSH
	db 23, HONE_EDGE
	db 26, SLASH
	db 30, SHORYUKEN
	db 38, FLAMETHROWER
	db 46, HYPER_BEAM
	db 54, WYRM_WRATH
	db 60, FIRE_BLAST
	db 0

WartortleEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 36, BLASTOISE
	db 0
; Learnset
	db 6, BUBBLE
	db 8, HARDEN
	db 11, SUPER_SOAK
	db 14, LOW_KICK
	db 18, BITE
	db 23, SHELL_GAME
	db 28, CLAMP
	db 33, DIZZY_PUNCH
	db 35, BLOOD_RUSH
	db 42, METEOR_DRIVE
	db 50, HYDRO_PUMP
	db 0

CharizardEvosMoves:
; Evolutions
	db 0
; Learnset
	db 6, SMOKESCREEN
	db 9, EMBER
	db 12, SEISMIC_TOSS
	db 15, BELLOW
	db 18, HEAT_RUSH
	db 23, HONE_EDGE
	db 26, SLASH
	db 30, SHORYUKEN
	db 38, FLAMETHROWER
	db 46, HYPER_BEAM
	db 54, WYRM_WRATH
	db 60, FIRE_BLAST
	db 0

OddishEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 21, GLOOM
	db 0
; Learnset
	db 7, POISONPOWDER
	db 11, ACID
	db 15, ADAPTATION
	db 17, STUN_SPORE
	db 19, MEGA_DRAIN
	db 23, PHANTASM
	db 28, SLEEP_POWDER
	db 36, SLUDGE_BOMB
	db 45, TOXIC
	db 50, SENBONZAKURA
	db 57, EMETIC_PURGE
	db 0

GloomEvosMoves:
; Evolutions
	db EVOLVE_ITEM, LEAF_STONE, 1, VILEPLUME
	db 0
; Learnset
	db 7, POISONPOWDER
	db 11, ACID
	db 15, ADAPTATION
	db 17, STUN_SPORE
	db 19, MEGA_DRAIN
	db 23, PHANTASM
	db 28, SLEEP_POWDER
	db 36, SLUDGE_BOMB
	db 45, TOXIC
	db 50, SENBONZAKURA
	db 57, EMETIC_PURGE
	db 0

VileplumeEvosMoves:
; Evolutions
	db 0
; Learnset
	db 7, POISONPOWDER
	db 11, ACID
	db 15, ADAPTATION
	db 17, STUN_SPORE
	db 19, MEGA_DRAIN
	db 23, PHANTASM
	db 28, SLEEP_POWDER
	db 36, SLUDGE_BOMB
	db 45, TOXIC
	db 50, SENBONZAKURA
	db 57, EMETIC_PURGE
	db 0

BellsproutEvosMoves:
; Evolutions
	db EVOLVE_LEVEL, 21, WEEPINBELL
	db 0
; Learnset
	db 13, POISONPOWDER
	db 16, ACID
	db 19, MEGA_DRAIN
	db 22, STUN_SPORE
	db 25, POWER_BIND
	db 28, RAZOR_LEAF
	db 34, SLEEP_POWDER
	db 42, VENOM_LASH
	db 48, EGG_BOMB
	db 54, LEECH_SEED
	db 58, ADAPTATION
	db 0

WeepinbellEvosMoves:
; Evolutions
	db EVOLVE_ITEM, LEAF_STONE, 1, VICTREEBEL
	db 0
; Learnset
	db 13, POISONPOWDER
	db 16, ACID
	db 19, MEGA_DRAIN
	db 22, STUN_SPORE
	db 25, POWER_BIND
	db 28, RAZOR_LEAF
	db 34, SLEEP_POWDER
	db 42, VENOM_LASH
	db 48, EGG_BOMB
	db 54, LEECH_SEED
	db 58, ADAPTATION
	db 0

VictreebelEvosMoves:
; Evolutions
	db 0
; Learnset
	db 13, POISONPOWDER
	db 16, ACID
	db 19, MEGA_DRAIN
	db 22, STUN_SPORE
	db 25, POWER_BIND
	db 28, RAZOR_LEAF
	db 34, SLEEP_POWDER
	db 42, VENOM_LASH
	db 48, EGG_BOMB
	db 54, LEECH_SEED
	db 58, ADAPTATION
	db 0

